# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CauHinhMaNhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tien_to",
                    models.CharField(
                        default="NV", max_length=5, verbose_name="Tiền tố"
                    ),
                ),
                (
                    "do_dai_so",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Độ dài phần số"
                    ),
                ),
                (
                    "so_hien_tai",
                    models.PositiveIntegerField(default=0, verbose_name="Số hiện tại"),
                ),
            ],
            options={
                "verbose_name_plural": "Cấu hình Mã nhân viên",
            },
        ),
        migrations.CreateModel(
            name="ChucDanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_chuc_danh",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên chức danh"
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "nhom_quyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Nhóm quyền",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chức danh",
                "verbose_name_plural": "Danh mục Chức danh",
            },
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nhan_vien",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Mã số",
                    ),
                ),
                (
                    "anh_the",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="anh_the/",
                        verbose_name="Ảnh thẻ",
                    ),
                ),
                (
                    "ho_ten",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Họ và Tên"
                    ),
                ),
                (
                    "ngay_sinh",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gioi_tinh",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=1,
                        null=True,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "sdt_chinh",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="SĐT chính",
                    ),
                ),
                (
                    "so_cccd",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="CCCD",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "dia_chi_thuong_tru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Thường trú"
                    ),
                ),
                (
                    "dia_chi_tam_tru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tạm trú"
                    ),
                ),
                (
                    "nguoi_lien_he_khan_cap",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Liên hệ khẩn"
                    ),
                ),
                (
                    "sdt_khan_cap",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="SĐT khẩn"
                    ),
                ),
                (
                    "ngay_vao_lam",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày vào làm"
                    ),
                ),
                (
                    "trang_thai_lam_viec",
                    models.CharField(
                        choices=[
                            ("THUVIEC", "Thử việc"),
                            ("CHINHTHUC", "Chính thức"),
                            ("TAMHOAN", "Tạm hoãn"),
                            ("NGHIVIEC", "Đã nghỉ việc"),
                        ],
                        default="THUVIEC",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "loai_hop_dong",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XDTH", "Xác định thời hạn"),
                            ("KXDTH", "Không xác định thời hạn"),
                            ("THOIVU", "Thời vụ"),
                        ],
                        max_length=10,
                        verbose_name="Hợp đồng",
                    ),
                ),
                (
                    "so_tai_khoan",
                    models.CharField(blank=True, max_length=20, verbose_name="STK"),
                ),
                (
                    "ngan_hang",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ngân hàng"
                    ),
                ),
                (
                    "chi_nhanh_ngan_hang",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Chi nhánh"
                    ),
                ),
                (
                    "chuc_danh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.chucdanh",
                        verbose_name="Chức danh",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhan_vien",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản hệ thống",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Danh sách Nhân viên",
                "ordering": ["ma_nhan_vien"],
            },
        ),
        migrations.CreateModel(
            name="LichSuCongTac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ngay_bat_dau",
                    models.DateField(db_index=True, verbose_name="Ngày bắt đầu"),
                ),
                (
                    "ngay_ket_thuc",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                (
                    "chuc_danh_kiem_nhiem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.chucdanh",
                        verbose_name="Chức danh kiêm nhiệm",
                    ),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Mục tiêu",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_cong_tac",
                        to="users.nhanvien",
                    ),
                ),
                (
                    "quan_ly_truc_tiep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nhan_vien_cap_duoi",
                        to="users.nhanvien",
                        verbose_name="Quản lý trực tiếp",
                    ),
                ),
            ],
            options={
                "ordering": ["-ngay_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="HocVan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "truong_dao_tao",
                    models.CharField(max_length=255, verbose_name="Trường đào tạo"),
                ),
                (
                    "chuyen_nganh",
                    models.CharField(max_length=255, verbose_name="Chuyên ngành"),
                ),
                ("trinh_do", models.CharField(max_length=100, verbose_name="Trình độ")),
                ("tu_ngay", models.DateField(verbose_name="Từ ngày")),
                ("den_ngay", models.DateField(verbose_name="Đến ngày")),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoc_van",
                        to="users.nhanvien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BangCapChungChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_bang_cap",
                    models.CharField(max_length=255, verbose_name="Tên bằng cấp"),
                ),
                ("noi_cap", models.CharField(max_length=255, verbose_name="Nơi cấp")),
                ("ngay_cap", models.DateField(verbose_name="Ngày cấp")),
                (
                    "ngay_het_han",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bang_cap/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bang_cap",
                        to="users.nhanvien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhongBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_phong_ban",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên phòng ban"
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "nhom_quyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Nhóm quyền mặc định",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng ban",
                "verbose_name_plural": "Danh mục Phòng ban",
            },
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="phong_ban",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.phongban",
                verbose_name="Phòng ban",
            ),
        ),
    ]
