# Generated by Django 5.2.5 on 2026-03-20 12:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bangcapchungchi",
            options={
                "verbose_name": "Bằng cấp",
                "verbose_name_plural": "Bằng cấp & Chứng chỉ",
            },
        ),
        migrations.AlterModelOptions(
            name="cauhinhmanhanvien",
            options={
                "verbose_name": "Cấu hình Mã nhân viên",
                "verbose_name_plural": "Cấu hình Mã nhân viên",
            },
        ),
        migrations.AlterModelOptions(
            name="hocvan",
            options={
                "verbose_name": "Học vấn",
                "verbose_name_plural": "Quá trình Học vấn",
            },
        ),
        migrations.AlterModelOptions(
            name="lichsucongtac",
            options={
                "ordering": ["-ngay_bat_dau"],
                "verbose_name": "Lịch sử công tác",
                "verbose_name_plural": "Lịch sử công tác",
            },
        ),
        migrations.AlterField(
            model_name="hocvan",
            name="den_ngay",
            field=models.DateField(blank=True, null=True, verbose_name="Đến ngày"),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_chinh",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                help_text="Nhập số điện thoại (VD: 0912345678)",
                max_length=128,
                null=True,
                region="VN",
                verbose_name="SĐT chính",
            ),
        ),
    ]
