# Generated by Django 4.x on 2026-05-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_danh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_nhan_vien', to='users.chucdanh', verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='phong_ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_nhan_vien', to='users.phongban', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='hocvan',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_hoc_van', to='users.nhanvien'),
        ),
        migrations.AlterField(
            model_name='bangcapchungchi',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_bang_cap', to='users.nhanvien'),
        ),
        migrations.AlterField(
            model_name='lichsucongtac',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_lich_su_cong_tac', to='users.nhanvien'),
        ),
        migrations.AlterField(
            model_name='lichsucongtac',
            name='quan_ly_truc_tiep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_nhan_vien_cap_duoi', to='users.nhanvien', verbose_name='Quản lý trực tiếp'),
        ),
    ]