# Generated by Django 5.2.5 on 2026-03-21 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_bangcapchungchi_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhanvien",
            name="loai_hop_dong",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XDTH", "Xác định thời hạn"),
                    ("KXDTH", "Không xác định thời hạn"),
                    ("THOIVU", "Thời vụ"),
                ],
                max_length=50,
                verbose_name="Hợp đồng",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_chinh",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Nhập 10 số (VD: 0912345678)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại không hợp lệ. Vui lòng nhập 10 chữ số bắt đầu bằng số 0 (VD: 0912345678).",
                        regex="^0\\d{9}$",
                    )
                ],
                verbose_name="SĐT chính",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_khan_cap",
            field=models.CharField(blank=True, max_length=20, verbose_name="SĐT khẩn"),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="so_tai_khoan",
            field=models.CharField(blank=True, max_length=50, verbose_name="STK"),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="trang_thai_lam_viec",
            field=models.CharField(
                choices=[
                    ("THUVIEC", "Thử việc"),
                    ("CHINHTHUC", "Chính thức"),
                    ("TAMHOAN", "Tạm hoãn"),
                    ("NGHIVIEC", "Đã nghỉ việc"),
                ],
                default="THUVIEC",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
    ]
