# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chucdanh",
            options={
                "verbose_name": "Chức danh",
                "verbose_name_plural": "1. Danh mục Chức danh",
            },
        ),
        migrations.AlterModelOptions(
            name="nhanvien",
            options={
                "ordering": ["ma_nhan_vien"],
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "3. Danh sách Nhân viên",
            },
        ),
        migrations.AlterModelOptions(
            name="phongban",
            options={
                "verbose_name": "Phòng ban",
                "verbose_name_plural": "2. Danh mục Phòng ban",
            },
        ),
        migrations.AlterField(
            model_name="chucdanh",
            name="nhom_quyen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Nhóm quyền quản trị",
            ),
        ),
        migrations.AlterField(
            model_name="lichsucongtac",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="anh_the",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="anh_the/",
                verbose_name="Ảnh thẻ hồ sơ",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="dia_chi_tam_tru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ tạm trú"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="dia_chi_thuong_tru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ thường trú"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email cá nhân",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="loai_hop_dong",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XDTH", "Xác định thời hạn"),
                    ("KXDTH", "Không xác định thời hạn"),
                    ("THOIVU", "Thời vụ"),
                ],
                max_length=50,
                verbose_name="Loại hợp đồng",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="ma_nhan_vien",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Mã số NV",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="nguoi_lien_he_khan_cap",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Người liên hệ khẩn cấp"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_chinh",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Định dạng: 0xxxxxxxxx (10 số)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại không hợp lệ. Vui lòng nhập 10 chữ số bắt đầu bằng số 0 (VD: 0912345678).",
                        regex="^0\\d{9}$",
                    )
                ],
                verbose_name="Số điện thoại",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_khan_cap",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="SĐT khẩn cấp"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="so_cccd",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Số CCCD/CMND",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="so_tai_khoan",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Số tài khoản"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="trang_thai_lam_viec",
            field=models.CharField(
                choices=[
                    ("THUVIEC", "Thử việc"),
                    ("CHINHTHUC", "Chính thức"),
                    ("TAMHOAN", "Tạm hoãn"),
                    ("NGHIVIEC", "Đã nghỉ việc"),
                ],
                default="THUVIEC",
                max_length=50,
                verbose_name="Trạng thái nhân sự",
            ),
        ),
    ]
