# Generated by Django 5.2.5 on 2026-06-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_update_related_names"),
        ("users", "0004_alter_chucdanh_options_alter_nhanvien_options_and_more"),
    ]

    operations = []
