# Generated by Django 5.2.5 on 2026-06-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_20260602_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="nhanvien",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="Token định danh thiết bị cho Firebase Cloud Messaging",
                max_length=255,
                null=True,
                verbose_name="FCM Token",
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="ngay_nghi_viec",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày nghỉ việc"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="so_cccd",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Số CCCD/CMND (Encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="so_tai_khoan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Số tài khoản (Encrypted)"
            ),
        ),
    ]
