# Generated by Django 5.2.5 on 2026-06-08 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_nhanvien_fcm_token_nhanvien_ngay_nghi_viec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
        migrations.AddField(
            model_name='phongban',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
    ]
