# Generated by SCMD Pro hardening patch v3.5.0 Phase 0.

from django.conf import settings
from django.db import migrations, models
import core.managers


def backfill_nhanvien_tenant_id(apps, schema_editor):
    NhanVien = apps.get_model("users", "NhanVien")
    organization_id = settings.SCMD_ORGANIZATION_ID
    NhanVien.objects.exclude(tenant_id=organization_id).update(tenant_id=organization_id)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_nhanvien_tenant_id_phongban_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhanvien",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=core.managers.organization_id,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.RunPython(backfill_nhanvien_tenant_id, migrations.RunPython.noop),
    ]
