# Generated by Codex for SCMD Pro access-scope hardening.

import core.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_nhanvien_tenant_scope_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("ma_vung", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Mã vùng")),
                ("ten_vung", models.CharField(max_length=255, verbose_name="Tên vùng")),
                ("mo_ta", models.TextField(blank=True, default="", verbose_name="Mô tả")),
            ],
            options={
                "verbose_name": "Vùng quản lý",
                "verbose_name_plural": "Vùng quản lý",
            },
        ),
        migrations.CreateModel(
            name="NhanVienRegionAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("starts_at", models.DateField(db_index=True, verbose_name="Hiệu lực từ")),
                ("ends_at", models.DateField(blank=True, db_index=True, null=True, verbose_name="Hiệu lực đến")),
                ("status", models.CharField(choices=[("ACTIVE", "Đang hiệu lực"), ("INACTIVE", "Ngưng hiệu lực")], db_index=True, default="ACTIVE", max_length=20, verbose_name="Trạng thái")),
                ("reason", models.TextField(blank=True, default="", verbose_name="Lý do phân vùng")),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phan_vung_da_gan", to="users.nhanvien", verbose_name="Người gán vùng")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_phan_vung_quan_ly", to="users.nhanvien", verbose_name="Nhân viên")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_nhan_vien_duoc_phan_vung", to="users.region", verbose_name="Vùng quản lý")),
            ],
            options={
                "verbose_name": "Phân công vùng cho nhân viên",
                "verbose_name_plural": "Phân công vùng cho nhân viên",
            },
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["tenant_id", "ten_vung"], name="user_region_tenant_name_idx"),
        ),
        migrations.AddIndex(
            model_name="nhanvienregionassignment",
            index=models.Index(fields=["tenant_id", "nhan_vien", "status"], name="user_regasg_tenant_staff_status_idx"),
        ),
        migrations.AddIndex(
            model_name="nhanvienregionassignment",
            index=models.Index(fields=["tenant_id", "region", "status"], name="user_regasg_tenant_region_status_idx"),
        ),
    ]
