# Generated by Codex for SCMD Pro tenant-scope forward-fix.

import core.managers
from django.conf import settings
from django.db import migrations, models


def backfill_lichsucongtac_tenant_id(apps, schema_editor):
    LichSuCongTac = apps.get_model("users", "LichSuCongTac")
    organization_id = settings.SCMD_ORGANIZATION_ID
    LichSuCongTac.objects.exclude(tenant_id=organization_id).update(tenant_id=organization_id)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_region_scope_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="lichsucongtac",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=core.managers.organization_id,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.RunPython(backfill_lichsucongtac_tenant_id, migrations.RunPython.noop),
    ]
