# Generated by Django 5.2.5 on 2026-06-11 for SCMD Pro migration-state alignment.

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_lichsucongtac_tenant_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nhanvienregionassignment",
            old_name="user_regasg_tenant_staff_status_idx",
            new_name="usr_rasg_t_stf_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="nhanvienregionassignment",
            old_name="user_regasg_tenant_region_status_idx",
            new_name="usr_rasg_t_reg_stat_idx",
        ),
        migrations.AlterField(
            model_name="phongban",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=core.managers.organization_id,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
    ]
