# Generated by GPT-5.5 Thinking for SCMD Pro HR business-domain completeness.

import core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_rename_user_regasg_tenant_staff_status_idx_usr_rasg_t_stf_stat_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HopDongLaoDong",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_hop_dong", models.CharField(db_index=True, max_length=64, verbose_name="Số hợp đồng")),
                ("loai_hop_dong", models.CharField(choices=[("XDTH", "Xác định thời hạn"), ("KXDTH", "Không xác định thời hạn"), ("THOIVU", "Thời vụ")], help_text="SSOT loại hợp đồng cho hồ sơ HĐLĐ; không dùng NhanVien.loai_hop_dong để xác định hiệu lực.", max_length=50, verbose_name="Loại hợp đồng")),
                ("ngay_ky", models.DateField(blank=True, null=True, verbose_name="Ngày ký")),
                ("ngay_hieu_luc", models.DateField(db_index=True, verbose_name="Ngày hiệu lực")),
                ("ngay_het_han", models.DateField(blank=True, db_index=True, help_text="Để trống với hợp đồng không xác định thời hạn.", null=True, verbose_name="Ngày hết hạn")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_SIGNATURE", "Chờ ký"), ("ACTIVE", "Đã ký/hiệu lực"), ("EXPIRING", "Sắp hết hạn"), ("EXPIRED", "Hết hạn"), ("TERMINATED", "Chấm dứt")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("muc_luong_co_ban", models.DecimalField(decimal_places=0, default=0, help_text="Giá trị tham chiếu trên hợp đồng. Payroll hiện tại không tự động lấy từ trường này.", max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Mức lương cơ bản")),
                ("phu_cap", models.DecimalField(decimal_places=0, default=0, help_text="Tổng phụ cấp tham chiếu trên hợp đồng; không tự động ghi đè cấu hình lương hiện tại.", max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Phụ cấp")),
                ("file_hop_dong", models.FileField(blank=True, null=True, upload_to="hop_dong_lao_dong/%Y/%m/", verbose_name="File hợp đồng")),
                ("nguon_ho_so", models.CharField(choices=[("HR_ADMIN", "Nhập từ HR Admin"), ("IMPORT", "Import dữ liệu"), ("LEGACY", "Legacy/đối soát cũ"), ("OTHER", "Nguồn khác")], default="HR_ADMIN", max_length=32, verbose_name="Nguồn hồ sơ")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt/ký xác nhận")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_hop_dong_lao_dong_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt/ký xác nhận")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_hop_dong_lao_dong", to="users.nhanvien", verbose_name="Nhân viên")),
            ],
            options={
                "verbose_name": "Hợp đồng lao động",
                "verbose_name_plural": "4. Hợp đồng lao động",
                "ordering": ["-ngay_hieu_luc", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_het_han"], name="usr_hdld_tenant_status_exp_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "trang_thai"], name="usr_hdld_tenant_staff_stat_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "so_hop_dong"), name="uq_hdld_tenant_so_hop_dong"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhuLucHopDongLaoDong",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_phu_luc", models.CharField(max_length=64, verbose_name="Số phụ lục")),
                ("ngay_ky", models.DateField(blank=True, null=True, verbose_name="Ngày ký")),
                ("ngay_hieu_luc", models.DateField(blank=True, null=True, verbose_name="Ngày hiệu lực")),
                ("ngay_het_han", models.DateField(blank=True, null=True, verbose_name="Ngày hết hạn")),
                ("noi_dung", models.TextField(blank=True, verbose_name="Nội dung phụ lục")),
                ("file_phu_luc", models.FileField(blank=True, null=True, upload_to="phu_luc_hop_dong_lao_dong/%Y/%m/", verbose_name="File phụ lục")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("hop_dong", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_phu_luc", to="users.hopdonglaodong", verbose_name="Hợp đồng lao động")),
            ],
            options={
                "verbose_name": "Phụ lục hợp đồng lao động",
                "verbose_name_plural": "Phụ lục hợp đồng lao động",
                "ordering": ["-ngay_hieu_luc", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "hop_dong", "so_phu_luc"), name="uq_plhdld_tenant_contract_no"),
                ],
            },
        ),
    ]
