# Generated by GPT-5.5 Thinking for SCMD Pro HR/business-domain Phase B.

import core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0012_hopdonglaodong_phuluc"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonNghiPhep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("ma_don", models.CharField(db_index=True, max_length=64, verbose_name="Mã đơn")),
                ("loai_nghi", models.CharField(choices=[("PHEP_NAM", "Phép năm"), ("KHONG_LUONG", "Nghỉ không lương"), ("OM_DAU", "Ốm đau"), ("VIEC_RIENG", "Việc riêng"), ("KHAC", "Khác")], default="PHEP_NAM", max_length=32, verbose_name="Loại nghỉ")),
                ("tu_ngay", models.DateField(db_index=True, verbose_name="Từ ngày")),
                ("den_ngay", models.DateField(db_index=True, verbose_name="Đến ngày")),
                ("so_ngay", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số ngày")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("REJECTED", "Từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ly_do", models.TextField(blank=True, verbose_name="Lý do")),
                ("file_minh_chung", models.FileField(blank=True, null=True, upload_to="don_nghi_phep/%Y/%m/", verbose_name="File minh chứng")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_don_nghi_phep_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_don_nghi_phep", to="users.nhanvien", verbose_name="Nhân viên")),
            ],
            options={
                "verbose_name": "Đơn nghỉ phép",
                "verbose_name_plural": "5. Đơn nghỉ phép",
                "ordering": ["-tu_ngay", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "tu_ngay"], name="usr_leave_tenant_stat_from_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "tu_ngay"], name="usr_leave_t_staff_from_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "ma_don"), name="uq_leave_tenant_code")],
            },
        ),
        migrations.CreateModel(
            name="QuyetDinhNghiViec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_quyet_dinh", models.CharField(db_index=True, max_length=64, verbose_name="Số quyết định")),
                ("ngay_quyet_dinh", models.DateField(default=django.utils.timezone.localdate, verbose_name="Ngày quyết định")),
                ("ngay_hieu_luc", models.DateField(db_index=True, verbose_name="Ngày hiệu lực")),
                ("ly_do_nghi", models.TextField(blank=True, verbose_name="Lý do nghỉ việc")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("EFFECTIVE", "Có hiệu lực"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("file_quyet_dinh", models.FileField(blank=True, null=True, upload_to="quyet_dinh_nghi_viec/%Y/%m/", verbose_name="File quyết định")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_quyet_dinh_nghi_viec_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_quyet_dinh_nghi_viec", to="users.nhanvien", verbose_name="Nhân viên")),
            ],
            options={
                "verbose_name": "Quyết định nghỉ việc",
                "verbose_name_plural": "6. Quyết định nghỉ việc",
                "ordering": ["-ngay_hieu_luc", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_hieu_luc"], name="usr_exit_tenant_stat_eff_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "trang_thai"], name="usr_exit_tenant_staff_stat_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_quyet_dinh"), name="uq_exit_tenant_decision_no")],
            },
        ),
        migrations.CreateModel(
            name="HoSoBaoHiem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_bao_hiem", models.CharField(db_index=True, max_length=64, verbose_name="Số sổ/thẻ bảo hiểm")),
                ("loai_bao_hiem", models.CharField(choices=[("BHXH", "BHXH"), ("BHYT", "BHYT"), ("BHTN", "BHTN"), ("BAO_HIEM_KHAC", "Bảo hiểm khác")], default="BHXH", max_length=32, verbose_name="Loại bảo hiểm")),
                ("ngay_tham_gia", models.DateField(db_index=True, verbose_name="Ngày tham gia")),
                ("ngay_ket_thuc", models.DateField(blank=True, db_index=True, null=True, verbose_name="Ngày kết thúc")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("ACTIVE", "Đang hiệu lực"), ("PAUSED", "Tạm dừng"), ("TERMINATED", "Đã chấm dứt")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("file_ho_so", models.FileField(blank=True, null=True, upload_to="ho_so_bao_hiem/%Y/%m/", verbose_name="File hồ sơ bảo hiểm")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_ho_so_bao_hiem_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_ho_so_bao_hiem", to="users.nhanvien", verbose_name="Nhân viên")),
            ],
            options={
                "verbose_name": "Hồ sơ bảo hiểm",
                "verbose_name_plural": "7. Hồ sơ bảo hiểm",
                "ordering": ["-ngay_tham_gia", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_ket_thuc"], name="usr_ins_tenant_stat_end_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "loai_bao_hiem"], name="usr_ins_tenant_staff_type_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "nhan_vien", "loai_bao_hiem", "so_bao_hiem"), name="uq_ins_tenant_staff_type_no")],
            },
        ),
        migrations.CreateModel(
            name="OffboardingChecklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("thu_hoi_dong_phuc", models.BooleanField(default=False, verbose_name="Thu hồi đồng phục/công cụ")),
                ("ban_giao_tai_san", models.BooleanField(default=False, verbose_name="Bàn giao tài sản")),
                ("khoa_tai_khoan", models.BooleanField(default=False, verbose_name="Khóa/thu hồi tài khoản")),
                ("chot_cong", models.BooleanField(default=False, verbose_name="Chốt công")),
                ("quyet_toan_luong", models.BooleanField(default=False, verbose_name="Quyết toán lương")),
                ("hoan_tat", models.BooleanField(db_index=True, default=False, verbose_name="Hoàn tất offboarding")),
                ("ngay_hoan_tat", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm hoàn tất")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nguoi_xac_nhan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_checklist_offboarding_xac_nhan", to=settings.AUTH_USER_MODEL, verbose_name="Người xác nhận")),
                ("quyet_dinh", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_ban_giao", to="users.quyetdinhnghiviec", verbose_name="Quyết định nghỉ việc")),
            ],
            options={
                "verbose_name": "Checklist nghỉ việc",
                "verbose_name_plural": "Checklist nghỉ việc",
                "ordering": ["hoan_tat", "-created_at"],
                "indexes": [models.Index(fields=["tenant_id", "hoan_tat"], name="usr_offboard_tenant_done_idx")],
            },
        ),
    ]
