# -*- coding: utf-8 -*-
"""Static contracts for the KTC Việt Nam Security Group demo seed scenario."""

import re
import unicodedata

from django.test import SimpleTestCase

from main.management.commands.seed_scmd_demo import (
    BRANCHES,
    COMPANY_PROFILE,
    DASHBOARD_ACCOUNTS,
    DEFAULT_DEMO_PASSWORD,
    DEFAULT_GUARDS,
    DEFAULT_PROFILE,
    DEFAULT_SCENARIO_KEY,
    PROFILE_SPECS,
)


class KTCVietNamSecuritySeedContractTests(SimpleTestCase):
    def test_default_profile_is_light_for_low_ram_demo_vm(self):
        self.assertEqual(DEFAULT_PROFILE, "light")
        self.assertEqual(DEFAULT_GUARDS, 60)
        light = PROFILE_SPECS["light"]
        self.assertEqual(light.guards, 60)
        self.assertEqual(light.days, 21)
        self.assertEqual(light.past_days, 7)
        self.assertEqual(light.target_count, 24)
        self.assertEqual(light.incident_count, 36)
        self.assertEqual(light.headcount_checks, 72)
        self.assertEqual(light.inventory_issue_slips, 16)
        self.assertEqual(light.payroll_periods, 1)

    def test_profiles_keep_full_contract_available_without_defaulting_to_it(self):
        full = PROFILE_SPECS["full"]
        self.assertEqual(sum(branch.guard_count for branch in BRANCHES), 200)
        self.assertEqual({branch.key: branch.guard_count for branch in BRANCHES}, {"hanoi": 95, "danang": 45, "saigon": 60})
        self.assertEqual(full.guards, 200)
        self.assertEqual(full.days, 45)
        self.assertEqual(full.past_days, 15)
        self.assertEqual(full.target_count, 35)

    def test_default_demo_password_contract(self):
        self.assertEqual(DEFAULT_DEMO_PASSWORD, "Abcd@1234")

    def test_dashboard_usernames_are_vietnamese_without_accents(self):
        username_pattern = re.compile(r"^[a-z0-9]+(?:\.[a-z0-9]+)*$")
        for username, *_rest in DASHBOARD_ACCOUNTS:
            normalized = unicodedata.normalize("NFKD", username).encode("ascii", "ignore").decode("ascii")
            self.assertEqual(username, normalized)
            self.assertRegex(username, username_pattern)

    def test_ktc_company_profile_contract(self):
        self.assertEqual(DEFAULT_SCENARIO_KEY, "ktc_viet_nam_security_group")
        self.assertEqual(COMPANY_PROFILE["ma_so_thue"], "0106004565")
        self.assertEqual(COMPANY_PROFILE["ten_cong_ty"], "KTC VIỆT NAM PRO.,JSC")
        self.assertIn("KTC VIỆT NAM", COMPANY_PROFILE["ten_phap_ly"])
        self.assertIn("Phan Đăng Lưu", COMPANY_PROFILE["dia_chi"])

    def test_required_branch_dashboard_accounts_exist(self):
        usernames = {row[0] for row in DASHBOARD_ACCOUNTS}
        for username in {
            "tonggiamdoc.hanoi",
            "truongvanhanh.hanoi",
            "truongnhansu.hanoi",
            "ketoantruong.hanoi",
            "thukho.hanoi",
            "truongkinhdoanh.hanoi",
            "giamdocchinhanh.danang",
            "kinhdoanh.danang",
            "thukho.danang",
            "giamdocchinhanh.saigon",
            "kinhdoanh.saigon",
            "thukho.saigon",
            "baove.hn001",
            "baove.dn001",
            "baove.sg001",
        }:
            # Guard users are generated by scale, not listed in DASHBOARD_ACCOUNTS.
            if username.startswith("baove."):
                continue
            self.assertIn(username, usernames)

    def test_seed_command_does_not_overwrite_shared_reference_data(self):
        from pathlib import Path
        source = Path("main/management/commands/seed_scmd_demo.py").read_text(encoding="utf-8")
        forbidden = [
            "PhongBan.objects.update_or_create",
            "ChucDanh.objects.update_or_create",
            "CaLamViec.objects.update_or_create",
            "BangLuongThang.objects.update_or_create",
        ]
        for pattern in forbidden:
            self.assertNotIn(pattern, source)
        self.assertIn('CaLamViec.objects.get_or_create', source)
        self.assertIn('ten_ca__startswith=DEMO_PREFIX', source)
        self.assertIn('real payroll period exists', source)
