# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoHoiKinhDoanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_co_hoi",
                    models.CharField(max_length=255, verbose_name="Tên cơ hội"),
                ),
                (
                    "gia_tri_uoc_tinh",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá trị ước tính",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("MOI", "Mới tiếp nhận"),
                            ("LIENHE", "Đang liên hệ"),
                            ("BAOGIA", "Đã báo giá"),
                            ("THUONGLUONG", "Đang thương thảo"),
                            ("THANHCONG", "Chốt hợp đồng (Thắng)"),
                            ("THATBAI", "Thất bại (Thua)"),
                        ],
                        default="MOI",
                        max_length=20,
                        verbose_name="Giai đoạn",
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cơ hội Kinh doanh",
                "verbose_name_plural": "2. Pipeline (Cơ hội)",
            },
        ),
        migrations.CreateModel(
            name="HopDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_hop_dong",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Số hợp đồng",
                    ),
                ),
                (
                    "ngay_ky",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày ký"
                    ),
                ),
                (
                    "ngay_hieu_luc",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày hiệu lực"
                    ),
                ),
                (
                    "ngay_het_han",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "gia_tri",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá trị Hợp đồng (Tháng)",
                    ),
                ),
                (
                    "file_hop_dong",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="hop_dong/",
                        verbose_name="File Scan",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("HIEU_LUC", "Đang hiệu lực"),
                            ("SAP_HET_HAN", "Sắp hết hạn"),
                            ("DA_THANH_LY", "Đã thanh lý/Hết hạn"),
                        ],
                        db_index=True,
                        default="HIEU_LUC",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng Dịch vụ",
                "verbose_name_plural": "3. Quản lý Hợp đồng",
            },
        ),
        migrations.CreateModel(
            name="KhachHangTiemNang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Tên công ty/Khách hàng",
                    ),
                ),
                (
                    "nguoi_lien_he",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Người liên hệ"
                    ),
                ),
                ("sdt", models.CharField(max_length=20, verbose_name="Số điện thoại")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "nguon",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website/Google"),
                            ("GIOI_THIEU", "Người quen giới thiệu"),
                            ("MXH", "Mạng xã hội (FB/Zalo)"),
                            ("KHAC", "Khác"),
                        ],
                        default="KHAC",
                        max_length=50,
                        verbose_name="Nguồn",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("MOI", "Mới tiếp nhận"),
                            ("TIEM_NANG", "Đang chăm sóc"),
                            ("BAO_GIA", "Đã gửi báo giá"),
                            ("CHOT_HOP_DONG", "Đã ký hợp đồng"),
                            ("HUY", "Khách hủy/Thất bại"),
                        ],
                        default="MOI",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, verbose_name="Ghi chú chăm sóc"),
                ),
                ("ngay_tao", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Khách hàng & Leads",
                "verbose_name_plural": "1. Danh sách Khách hàng",
                "ordering": ["-ngay_tao"],
            },
        ),
        migrations.CreateModel(
            name="MucTieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_muc_tieu",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tên mục tiêu"
                    ),
                ),
                ("dia_chi", models.TextField(verbose_name="Địa chỉ Mục tiêu")),
                (
                    "vi_do",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Vĩ độ (Lat)"
                    ),
                ),
                (
                    "kinh_do",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Kinh độ (Lng)"
                    ),
                ),
                (
                    "ban_kinh_cho_phep",
                    models.IntegerField(default=100, verbose_name="Bán kính (m)"),
                ),
                (
                    "luong_khoan_bao_ve",
                    models.DecimalField(
                        decimal_places=0,
                        default=6000000,
                        help_text="Mức lương chuẩn cho 1 tháng làm đủ công",
                        max_digits=12,
                        verbose_name="Lương khoán (Tháng)",
                    ),
                ),
                (
                    "so_gio_mot_ngay",
                    models.FloatField(
                        default=12.0,
                        help_text="VD: 12h. Hệ thống sẽ tự nhân với số ngày trong tháng (28/30/31).",
                        verbose_name="Giờ chuẩn/ngày",
                    ),
                ),
                (
                    "tien_chuyen_can",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Tiền chuyên cần (Full)",
                    ),
                ),
                (
                    "tru_nghi_1_ngay",
                    models.DecimalField(
                        decimal_places=0,
                        default=400000,
                        max_digits=12,
                        verbose_name="Trừ nghỉ 1 ngày",
                    ),
                ),
                (
                    "tru_nghi_2_ngay",
                    models.DecimalField(
                        decimal_places=0,
                        default=300000,
                        max_digits=12,
                        verbose_name="Trừ nghỉ 2 ngày",
                    ),
                ),
                (
                    "tru_nghi_3_ngay",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Trừ nghỉ 3+ ngày",
                    ),
                ),
                (
                    "nguoi_lien_he",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Người liên hệ tại Mục tiêu",
                    ),
                ),
                (
                    "sdt_lien_he",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SĐT liên hệ"
                    ),
                ),
                (
                    "so_luong_nhan_vien",
                    models.IntegerField(default=1, verbose_name="Định biên nhân sự"),
                ),
            ],
            options={
                "verbose_name": "Mục tiêu Bảo vệ",
                "verbose_name_plural": "4. Danh sách Mục tiêu",
            },
        ),
    ]
