# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohoikinhdoanh",
            name="nguoi_phu_trach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Sales phụ trách",
            ),
        ),
        migrations.AddField(
            model_name="hopdong",
            name="co_hoi",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hop_dong",
                to="clients.cohoikinhdoanh",
                verbose_name="Từ Cơ hội",
            ),
        ),
        migrations.AddField(
            model_name="hopdong",
            name="khach_hang_cu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hop_dong_cu",
                to="clients.khachhangtiemnang",
            ),
        ),
        migrations.AddField(
            model_name="cohoikinhdoanh",
            name="khach_hang_tiem_nang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.khachhangtiemnang",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AddField(
            model_name="muctieu",
            name="hop_dong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muc_tieu",
                to="clients.hopdong",
                verbose_name="Thuộc Hợp đồng",
            ),
        ),
        migrations.AddField(
            model_name="muctieu",
            name="quan_ly_muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu_quan_ly",
                to="users.nhanvien",
                verbose_name="Chỉ huy trưởng",
            ),
        ),
    ]
