# Generated by Django 4.x on 2026-05-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohoikinhdoanh',
            name='khach_hang_tiem_nang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_co_hoi_kinh_doanh', to='clients.khachhangtiemnang', verbose_name='KhÃ¡ch hÃ ng liÃªn quan'),
        ),
        migrations.AlterField(
            model_name='cohoikinhdoanh',
            name='nguoi_phu_trach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_co_hoi_kinh_doanh', to='users.nhanvien', verbose_name='NhÃ¢n viÃªn Sales phá»¥ trÃ¡ch'),
        ),
        migrations.AlterField(
            model_name='muctieu',
            name='hop_dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_muc_tieu', to='clients.hopdong', verbose_name='Thuá»™c Há»£p Ä‘á»“ng kinh táº¿'),
        ),
        migrations.AlterField(
            model_name='muctieu',
            name='quan_ly_muc_tieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_muc_tieu_quan_ly', to='users.nhanvien', verbose_name='Chá»‰ huy trÆ°á»Ÿng má»¥c tiÃªu'),
        ),
        migrations.AddField(
            model_name='muctieu',
            name='quan_ly_vung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_muc_tieu_phu_trach_vung', to='users.nhanvien', verbose_name='Quáº£n lÃ½ vÃ¹ng phá»¥ trÃ¡ch (Regional Manager)'),
        ),
    ]