# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="gia_tri_uoc_tinh",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Giá trị dự kiến (VNĐ)",
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="khach_hang_tiem_nang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.khachhangtiemnang",
                verbose_name="Khách hàng liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="ngay_tao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ngày tạo cơ hội"
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="nguoi_phu_trach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Nhân viên Sales phụ trách",
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="ten_co_hoi",
            field=models.CharField(
                help_text="Ví dụ: Gói bảo vệ mục tiêu Chung cư Vincity Q9",
                max_length=255,
                verbose_name="Tên cơ hội/Dự án",
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("MOI", "Mới tiếp nhận"),
                    ("LIENHE", "Đang liên hệ"),
                    ("BAOGIA", "Đã báo giá"),
                    ("THUONGLUONG", "Đang thương thảo"),
                    ("THANHCONG", "Chốt hợp đồng (Thắng)"),
                    ("THATBAI", "Thất bại (Thua)"),
                ],
                default="MOI",
                max_length=20,
                verbose_name="Giai đoạn bán hàng",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="co_hoi",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hop_dong",
                to="clients.cohoikinhdoanh",
                verbose_name="Chuyển đổi từ cơ hội",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="file_hop_dong",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="hop_dong/",
                verbose_name="Bản Scan hợp đồng (PDF/Image)",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="gia_tri",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Số tiền thu về từ khách hàng hàng tháng.",
                max_digits=15,
                verbose_name="Giá trị Hợp đồng (Tháng)",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="khach_hang_cu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hop_dong_cu",
                to="clients.khachhangtiemnang",
                verbose_name="Chủ sở hữu hợp đồng",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="ngay_het_han",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Ngày kết thúc hợp đồng"
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="ngay_hieu_luc",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Ngày bắt đầu hiệu lực"
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="ngay_ky",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Ngày ký kết"
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="so_hop_dong",
            field=models.CharField(
                db_index=True,
                help_text="Mã định danh duy nhất của hợp đồng trên hệ thống.",
                max_length=100,
                unique=True,
                verbose_name="Số hợp đồng",
            ),
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("HIEU_LUC", "Đang hiệu lực"),
                    ("SAP_HET_HAN", "Sắp hết hạn (Dưới 30 ngày)"),
                    ("DA_THANH_LY", "Đã thanh lý/Hết hạn"),
                ],
                db_index=True,
                default="HIEU_LUC",
                max_length=20,
                verbose_name="Tình trạng hợp đồng",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="dia_chi",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ trụ sở"
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="ghi_chu",
            field=models.TextField(
                blank=True,
                help_text="Lịch sử trao đổi hoặc các lưu ý đặc biệt về khách hàng.",
                verbose_name="Ghi chú chăm sóc",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="ngay_tao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày khởi tạo hệ thống"
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="nguoi_lien_he",
            field=models.CharField(
                blank=True,
                help_text="Đầu mối liên hệ trực tiếp tại đơn vị khách hàng.",
                max_length=100,
                verbose_name="Người liên hệ",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="nguon",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Website/Google"),
                    ("GIOI_THIEU", "Người quen giới thiệu"),
                    ("MXH", "Mạng xã hội (FB/Zalo)"),
                    ("KHAC", "Khác"),
                ],
                default="KHAC",
                max_length=50,
                verbose_name="Nguồn khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="sdt",
            field=models.CharField(
                help_text="Số điện thoại di động hoặc hotline liên lạc.",
                max_length=20,
                verbose_name="Số điện thoại",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="ten_cong_ty",
            field=models.CharField(
                db_index=True,
                help_text="Tên pháp nhân trên giấy phép kinh doanh hoặc tên cá nhân khách hàng.",
                max_length=255,
                verbose_name="Tên công ty/Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="khachhangtiemnang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("MOI", "Mới tiếp nhận"),
                    ("TIEM_NANG", "Đang chăm sóc"),
                    ("BAO_GIA", "Đã gửi báo giá"),
                    ("CHOT_HOP_DONG", "Đã ký hợp đồng"),
                    ("HUY", "Khách hủy/Thất bại"),
                ],
                default="MOI",
                max_length=20,
                verbose_name="Trạng thái chăm sóc",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="ban_kinh_cho_phep",
            field=models.IntegerField(
                default=100,
                help_text="Phạm vi cho phép nhân viên Check-in/Check-out hợp lệ.",
                verbose_name="Bán kính kiểm soát (mét)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="dia_chi",
            field=models.TextField(
                help_text="Địa chỉ chi tiết nơi nhân viên an ninh thực hiện nhiệm vụ.",
                verbose_name="Địa chỉ triển khai mục tiêu",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="hop_dong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muc_tieu",
                to="clients.hopdong",
                verbose_name="Thuộc Hợp đồng kinh tế",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="kinh_do",
            field=models.FloatField(
                blank=True,
                help_text="Sử dụng Google Maps tọa độ để định vị mục tiêu.",
                null=True,
                verbose_name="Tọa độ Kinh độ (Lng)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="luong_khoan_bao_ve",
            field=models.DecimalField(
                decimal_places=0,
                default=6000000,
                help_text="Mức lương chuẩn cho 01 tháng làm đủ 100% công theo lịch trực.",
                max_digits=12,
                verbose_name="Lương khoán định mức (Tháng)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="nguoi_lien_he",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Đầu mối liên hệ tại mục tiêu"
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="quan_ly_muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu_quan_ly",
                to="users.nhanvien",
                verbose_name="Chỉ huy trưởng mục tiêu",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="sdt_lien_he",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="SĐT liên hệ mục tiêu"
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="so_gio_mot_ngay",
            field=models.FloatField(
                default=12.0,
                help_text="Số giờ ca trực tiêu chuẩn. Hệ thống sẽ tự nhân với số ngày trong tháng (28/30/31).",
                verbose_name="Định mức giờ trực/ngày",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="so_luong_nhan_vien",
            field=models.IntegerField(
                default=1,
                help_text="Số lượng nhân viên tối thiểu cần bố trí cho mục tiêu này.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Định biên quân số (Người)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="ten_muc_tieu",
            field=models.CharField(
                db_index=True,
                help_text="Ví dụ: Cổng chính, Kho hàng A, v.v.",
                max_length=255,
                verbose_name="Tên mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="tien_chuyen_can",
            field=models.DecimalField(
                decimal_places=0,
                default=1000000,
                help_text="Thưởng tối đa khi nhân viên đi làm đủ công và không vi phạm kỷ luật.",
                max_digits=12,
                verbose_name="Tiền thưởng chuyên cần tối đa",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="tru_nghi_1_ngay",
            field=models.DecimalField(
                decimal_places=0,
                default=400000,
                max_digits=12,
                verbose_name="Khấu trừ chuyên cần (nghỉ 1 ngày)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="tru_nghi_2_ngay",
            field=models.DecimalField(
                decimal_places=0,
                default=300000,
                max_digits=12,
                verbose_name="Khấu trừ chuyên cần (nghỉ 2 ngày)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="tru_nghi_3_ngay",
            field=models.DecimalField(
                decimal_places=0,
                default=1000000,
                max_digits=12,
                verbose_name="Khấu trừ chuyên cần (nghỉ từ 3 ngày trở lên)",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="vi_do",
            field=models.FloatField(
                blank=True,
                help_text="Sử dụng Google Maps tọa độ để định vị mục tiêu.",
                null=True,
                verbose_name="Tọa độ Vĩ độ (Lat)",
            ),
        ),
    ]
