# Generated by Django 5.2.5 on 2026-06-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_add_tenant_id_to_crm_models"),
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
    ]

    operations = []
