# Generated by Django 5.2.5 on 2026-06-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_merge_20260602_0856"),
        ("users", "0006_nhanvien_fcm_token_nhanvien_ngay_nghi_viec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="khach_hang_tiem_nang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_co_hoi_kinh_doanh",
                to="clients.khachhangtiemnang",
                verbose_name="Khách hàng liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="cohoikinhdoanh",
            name="nguoi_phu_trach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_co_hoi_kinh_doanh",
                to="users.nhanvien",
                verbose_name="Nhân viên Sales phụ trách",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="hop_dong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_muc_tieu",
                to="clients.hopdong",
                verbose_name="Thuộc Hợp đồng kinh tế",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="quan_ly_muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu_quan_ly",
                to="users.nhanvien",
                verbose_name="Chỉ huy trưởng mục tiêu",
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="quan_ly_vung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu_phu_trach_vung",
                to="users.nhanvien",
                verbose_name="Quản lý vùng phụ trách (Regional Manager)",
            ),
        ),
    ]
