# Generated by Codex for SCMD Pro region scope binding.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_region_scope_models"),
        ("clients", "0008_alter_cohoikinhdoanh_tenant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="muctieu",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="SSOT vùng vận hành dùng cho REGION scope của Quản lý vùng.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu",
                to="users.region",
                verbose_name="Vùng quản lý",
            ),
        ),
    ]
