# Generated by Codex for SCMD Pro region-scope SSOT alignment.

import django.db.models.deletion
from django.db import migrations, models


def backfill_cohoikinhdoanh_region(apps, schema_editor):
    MucTieu = apps.get_model("clients", "MucTieu")
    CoHoiKinhDoanh = apps.get_model("clients", "CoHoiKinhDoanh")

    for muc_tieu in (
        MucTieu.objects
        .filter(region__isnull=False, hop_dong__co_hoi__isnull=False)
        .select_related("hop_dong__co_hoi")
    ):
        co_hoi = muc_tieu.hop_dong.co_hoi
        if co_hoi and co_hoi.region_id is None:
            CoHoiKinhDoanh.objects.filter(pk=co_hoi.pk).update(region_id=muc_tieu.region_id)


def reverse_backfill_muctieu_region(apps, schema_editor):
    MucTieu = apps.get_model("clients", "MucTieu")

    for muc_tieu in (
        MucTieu.objects
        .filter(hop_dong__co_hoi__region__isnull=False)
        .select_related("hop_dong__co_hoi")
    ):
        co_hoi = muc_tieu.hop_dong.co_hoi
        if co_hoi and muc_tieu.region_id is None:
            MucTieu.objects.filter(pk=muc_tieu.pk).update(region_id=co_hoi.region_id)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_user_regasg_tenant_staff_status_idx_usr_rasg_t_stf_stat_idx_and_more"),
        ("clients", "0009_muctieu_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohoikinhdoanh",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="SSOT vùng vận hành dùng cho REGION scope của Quản lý vùng.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_muc_tieu",
                to="users.region",
                verbose_name="Vùng quản lý",
            ),
        ),
        migrations.RunPython(backfill_cohoikinhdoanh_region, reverse_backfill_muctieu_region),
        migrations.RemoveField(
            model_name="muctieu",
            name="region",
        ),
    ]
