# Generated by GPT-5.5 Thinking for SCMD Pro client-contract finance completeness.

from decimal import Decimal

import core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0010_remove_muctieu_region_cohoikinhdoanh_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhuLucHopDongDichVu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_phu_luc", models.CharField(db_index=True, max_length=64, verbose_name="Số phụ lục")),
                ("loai_phu_luc", models.CharField(choices=[("DIEU_CHINH_GIA", "Điều chỉnh giá"), ("BO_SUNG_MUC_TIEU", "Bổ sung mục tiêu"), ("GIA_HAN", "Gia hạn"), ("DIEU_CHINH_DIEU_KHOAN", "Điều chỉnh điều khoản"), ("KHAC", "Khác")], default="KHAC", max_length=32, verbose_name="Loại phụ lục")),
                ("ngay_ky", models.DateField(blank=True, null=True, verbose_name="Ngày ký")),
                ("ngay_hieu_luc", models.DateField(db_index=True, verbose_name="Ngày hiệu lực")),
                ("ngay_het_han", models.DateField(blank=True, db_index=True, null=True, verbose_name="Ngày hết hạn")),
                ("gia_tri_dieu_chinh", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=15, verbose_name="Giá trị điều chỉnh")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("ACTIVE", "Có hiệu lực"), ("EXPIRED", "Hết hiệu lực"), ("TERMINATED", "Chấm dứt")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("file_phu_luc", models.FileField(blank=True, null=True, upload_to="phu_luc_hop_dong_dich_vu/%Y/%m/", verbose_name="File phụ lục")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("hop_dong", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_phu_luc_dich_vu", to="clients.hopdong", verbose_name="Hợp đồng dịch vụ")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phu_luc_dich_vu_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
            ],
            options={
                "verbose_name": "Phụ lục hợp đồng dịch vụ",
                "verbose_name_plural": "4. Phụ lục hợp đồng dịch vụ",
                "ordering": ["-ngay_hieu_luc", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_het_han"], name="cli_pldv_tenant_stat_exp_idx"),
                    models.Index(fields=["tenant_id", "hop_dong", "trang_thai"], name="cli_pldv_tenant_hd_stat_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "hop_dong", "so_phu_luc"), name="uq_pldv_tenant_hd_no")],
            },
        ),
        migrations.CreateModel(
            name="BienBanNghiemThu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_bien_ban", models.CharField(db_index=True, max_length=64, verbose_name="Số biên bản")),
                ("tu_ngay", models.DateField(db_index=True, verbose_name="Nghiệm thu từ ngày")),
                ("den_ngay", models.DateField(db_index=True, verbose_name="Nghiệm thu đến ngày")),
                ("ngay_lap", models.DateField(default=django.utils.timezone.localdate, verbose_name="Ngày lập")),
                ("tong_gia_tri_nghiem_thu", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Tổng giá trị nghiệm thu")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_SIGNATURE", "Chờ ký"), ("SIGNED", "Đã ký"), ("REJECTED", "Từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("file_bien_ban", models.FileField(blank=True, null=True, upload_to="bien_ban_nghiem_thu/%Y/%m/", verbose_name="File biên bản")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt/ký")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("hop_dong", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_bien_ban_nghiem_thu", to="clients.hopdong", verbose_name="Hợp đồng dịch vụ")),
                ("muc_tieu", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_bien_ban_nghiem_thu", to="clients.muctieu", verbose_name="Mục tiêu")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_bien_ban_nghiem_thu_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt/ký")),
            ],
            options={
                "verbose_name": "Biên bản nghiệm thu",
                "verbose_name_plural": "5. Biên bản nghiệm thu",
                "ordering": ["-ngay_lap", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_lap"], name="cli_bbnt_tenant_stat_date_idx"),
                    models.Index(fields=["tenant_id", "hop_dong", "tu_ngay"], name="cli_bbnt_tenant_hd_from_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_bien_ban"), name="uq_bbnt_tenant_no")],
            },
        ),
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_hoa_don", models.CharField(db_index=True, max_length=64, verbose_name="Số hóa đơn")),
                ("ngay_phat_hanh", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Ngày phát hành")),
                ("ngay_den_han", models.DateField(blank=True, db_index=True, null=True, verbose_name="Ngày đến hạn")),
                ("tong_tien", models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Tổng tiền")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("ISSUED", "Đã phát hành"), ("PARTIALLY_PAID", "Thanh toán một phần"), ("PAID", "Đã thanh toán"), ("OVERDUE", "Quá hạn"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("file_hoa_don", models.FileField(blank=True, null=True, upload_to="hoa_don/%Y/%m/", verbose_name="File hóa đơn")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("bien_ban", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_hoa_don", to="clients.bienbannghiemthu", verbose_name="Biên bản nghiệm thu")),
                ("hop_dong", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_hoa_don", to="clients.hopdong", verbose_name="Hợp đồng dịch vụ")),
            ],
            options={
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "6. Hóa đơn",
                "ordering": ["-ngay_phat_hanh", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_den_han"], name="cli_inv_tenant_stat_due_idx"),
                    models.Index(fields=["tenant_id", "hop_dong", "ngay_phat_hanh"], name="cli_inv_tenant_hd_date_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_hoa_don"), name="uq_invoice_tenant_no")],
            },
        ),
        migrations.CreateModel(
            name="CongNo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_tham_chieu", models.CharField(db_index=True, max_length=64, verbose_name="Số tham chiếu công nợ")),
                ("ngay_den_han", models.DateField(db_index=True, verbose_name="Ngày đến hạn")),
                ("so_tien_phai_thu", models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền phải thu")),
                ("so_tien_da_thu", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền đã thu")),
                ("trang_thai", models.CharField(choices=[("OPEN", "Chưa thu"), ("PARTIAL", "Thu một phần"), ("PAID", "Đã thu đủ"), ("OVERDUE", "Quá hạn"), ("WRITTEN_OFF", "Xóa/điều chỉnh nợ")], db_index=True, default="OPEN", max_length=32, verbose_name="Trạng thái")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("hoa_don", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_cong_no", to="clients.hoadon", verbose_name="Hóa đơn")),
            ],
            options={
                "verbose_name": "Công nợ",
                "verbose_name_plural": "7. Công nợ",
                "ordering": ["ngay_den_han", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_den_han"], name="cli_debt_tenant_stat_due_idx"),
                    models.Index(fields=["tenant_id", "hoa_don", "trang_thai"], name="cli_debt_tenant_inv_stat_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_tham_chieu"), name="uq_debt_tenant_ref")],
            },
        ),
    ]
