# Generated by GPT-5.5 Thinking for SCMD Pro Phase E customer payment settlement.

from decimal import Decimal

import core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0011_contract_finance_phase_b_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThanhToanKhachHang",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("ma_phieu", models.CharField(db_index=True, max_length=64, verbose_name="Mã phiếu thanh toán")),
                ("ngay_thanh_toan", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Ngày thanh toán")),
                ("so_tien", models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền thanh toán")),
                ("hinh_thuc", models.CharField(choices=[("TIEN_MAT", "Tiền mặt"), ("CHUYEN_KHOAN", "Chuyển khoản"), ("KHAC", "Khác")], default="CHUYEN_KHOAN", max_length=32, verbose_name="Hình thức thanh toán")),
                ("ma_giao_dich", models.CharField(blank=True, db_index=True, max_length=128, verbose_name="Mã giao dịch/chứng từ ngân hàng")),
                ("file_chung_tu", models.FileField(blank=True, null=True, upload_to="thanh_toan_khach_hang/%Y/%m/", verbose_name="File chứng từ")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("RECEIVED", "Đã ghi nhận tiền"), ("ALLOCATED", "Đã phân bổ"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt/ghi nhận")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("hop_dong", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_thanh_toan_khach_hang", to="clients.hopdong", verbose_name="Hợp đồng dịch vụ")),
                ("khach_hang", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_thanh_toan_khach_hang", to="clients.khachhangtiemnang", verbose_name="Khách hàng")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_thanh_toan_khach_hang_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nguoi_ghi_nhan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_thanh_toan_khach_hang_da_ghi_nhan", to=settings.AUTH_USER_MODEL, verbose_name="Người ghi nhận")),
            ],
            options={
                "verbose_name": "Thanh toán khách hàng",
                "verbose_name_plural": "8. Thanh toán khách hàng",
                "ordering": ["-ngay_thanh_toan", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_thanh_toan"], name="cli_pay_tenant_stat_date_idx"),
                    models.Index(fields=["tenant_id", "hop_dong", "trang_thai"], name="cli_pay_tenant_hd_stat_idx"),
                    models.Index(fields=["tenant_id", "khach_hang", "ngay_thanh_toan"], name="cli_pay_tenant_cus_date_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "ma_phieu"), name="uq_payment_tenant_code")],
            },
        ),
        migrations.CreateModel(
            name="PhanBoThanhToanHoaDon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_tien", models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền phân bổ")),
                ("ngay_phan_bo", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Thời điểm phân bổ")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("cong_no", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cac_phan_bo_thanh_toan", to="clients.congno", verbose_name="Công nợ")),
                ("hoa_don", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cac_phan_bo_thanh_toan", to="clients.hoadon", verbose_name="Hóa đơn")),
                ("nguoi_phan_bo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phan_bo_thanh_toan_khach_hang", to=settings.AUTH_USER_MODEL, verbose_name="Người phân bổ")),
                ("thanh_toan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_phan_bo", to="clients.thanhtoankhachhang", verbose_name="Thanh toán khách hàng")),
            ],
            options={
                "verbose_name": "Phân bổ thanh toán hóa đơn",
                "verbose_name_plural": "9. Phân bổ thanh toán hóa đơn",
                "ordering": ["-ngay_phan_bo", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "thanh_toan", "ngay_phan_bo"], name="cli_alloc_tenant_pay_date_idx"),
                    models.Index(fields=["tenant_id", "hoa_don"], name="cli_alloc_tenant_inv_idx"),
                    models.Index(fields=["tenant_id", "cong_no"], name="cli_alloc_tenant_debt_idx"),
                ],
            },
        ),
    ]
