# Generated by Django 5.2.5 on 2026-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="mo_ta",
            field=models.TextField(
                blank=True,
                help_text="Hiển thị trên chân trang hoặc báo cáo",
                verbose_name="Giới thiệu ngắn",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="mst",
            field=models.CharField(
                blank=True,
                help_text="Mã số thuế pháp nhân để xuất hóa đơn và chứng từ",
                max_length=20,
                null=True,
                verbose_name="Mã số thuế",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="dia_chi",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ trụ sở"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, verbose_name="Email giao dịch"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Ảnh định dạng PNG/JPG, kích thước khuyến nghị 500x500px",
                null=True,
                upload_to="logos/%Y/",
                verbose_name="Logo thương hiệu",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="sdt",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Số điện thoại hotline"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="ten_cong_ty",
            field=models.CharField(max_length=255, verbose_name="Tên doanh nghiệp"),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website chính thức"),
        ),
    ]
