# Generated by Django 5.2.5 on 2026-06-02 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_companyprofile_mo_ta_companyprofile_mst_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Tạo mới"),
                            ("UPDATE", "Cập nhật"),
                            ("DELETE", "Xóa"),
                            ("ACCESS", "Truy cập dữ liệu nhạy cảm"),
                            ("EXECUTE", "Thực thi nghiệp vụ"),
                            ("LOGIN", "Đăng nhập"),
                        ],
                        max_length=20,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="VD: Operations, Accounting, HR",
                        max_length=50,
                        verbose_name="Phân hệ",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Tên Model"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID đối tượng",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Thay đổi chi tiết"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="Thông tin thiết bị"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Thời điểm"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="SUCCESS", max_length=20, verbose_name="Trạng thái"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        null=True,
                        verbose_name="Mã xác thực nội dung",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú/Lý do")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký hệ thống",
                "verbose_name_plural": "Nhật ký hệ thống (Audit Log)",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên Worker"
                    ),
                ),
                (
                    "last_ping",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Lần cuối phản hồi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Nhịp tim hệ thống",
                "verbose_name_plural": "Giám sát Workers (Heartbeat)",
            },
        ),
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
    ]
