# Generated by Django 5.2.5 on 2026-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auditlog_workerheartbeat_delete_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False, null=True, verbose_name='Tenant ID'),
        ),
    ]
