# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BienBanViPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_bien_ban",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "ngay_vi_pham",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời điểm vi phạm",
                    ),
                ),
                (
                    "loai_loi",
                    models.CharField(
                        choices=[
                            ("NGU_GAT", "😴 Ngủ gật"),
                            ("ROI_VI_TRI", "🏃 Rời vị trí"),
                            ("DUNG_DIEN_THOAI", "📱 Dùng điện thoại riêng"),
                            ("KHONG_DONG_PHUC", "👔 Sai đồng phục/Tác phong"),
                            ("KHAC", "📝 Khác"),
                        ],
                        default="NGU_GAT",
                        max_length=50,
                        verbose_name="Lỗi vi phạm",
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả chi tiết")),
                (
                    "bang_chung_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vipham/%Y/%m/",
                        verbose_name="Ảnh bằng chứng",
                    ),
                ),
                (
                    "hinh_thuc_xu_ly",
                    models.CharField(
                        choices=[
                            ("NHAC_NHO", "Nhắc nhở"),
                            ("CANH_CAO", "Cảnh cáo"),
                            ("PHAT_TIEN", "Phạt tiền"),
                            ("DINH_CHI", "Đình chỉ"),
                        ],
                        default="PHAT_TIEN",
                        max_length=20,
                        verbose_name="Hình thức",
                    ),
                ),
                (
                    "so_tien_phat",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Nhập số tiền nếu chọn Phạt tiền",
                        max_digits=12,
                        verbose_name="Số tiền phạt",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("CHO_DUYET", "⏳ Chờ duyệt"),
                            ("DA_DUYET", "✅ Đã duyệt"),
                            ("TU_CHOI", "❌ Từ chối"),
                        ],
                        default="CHO_DUYET",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Biên bản Vi phạm",
                "verbose_name_plural": "4. Quản lý Vi phạm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuoiHuanLuyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chu_de",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chủ đề"
                    ),
                ),
                ("thoi_gian", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dia_diem",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Địa điểm"
                    ),
                ),
            ],
            options={
                "ordering": ["-thoi_gian"],
            },
        ),
        migrations.CreateModel(
            name="DiemTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_diem", models.CharField(max_length=255, verbose_name="Tên điểm")),
                (
                    "ma_qr",
                    models.CharField(max_length=100, unique=True, verbose_name="Mã QR"),
                ),
                ("thu_tu", models.IntegerField(default=1, verbose_name="Thứ tự")),
                (
                    "vi_do",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="Vĩ độ (Lat)",
                    ),
                ),
                (
                    "kinh_do",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="Kinh độ (Lng)",
                    ),
                ),
                (
                    "ban_kinh_cho_phep",
                    models.IntegerField(
                        default=50,
                        help_text="Bán kính chấp nhận GPS yếu",
                        verbose_name="Bán kính (m)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm kiểm soát",
                "verbose_name_plural": "Điểm kiểm soát",
                "ordering": ["loai_tuan_tra", "thu_tu"],
            },
        ),
        migrations.CreateModel(
            name="DotThanhTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_den",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "quan_so_bao_cao",
                    models.IntegerField(default=0, verbose_name="Quân số (Lịch)"),
                ),
                (
                    "quan_so_thuc_te",
                    models.IntegerField(default=0, verbose_name="Quân số (Thực)"),
                ),
                (
                    "kiem_tra_so_sach",
                    models.BooleanField(default=True, verbose_name="Sổ sách?"),
                ),
                (
                    "kiem_tra_dong_phuc",
                    models.BooleanField(default=True, verbose_name="Đồng phục?"),
                ),
                (
                    "kiem_tra_cong_cu",
                    models.BooleanField(default=True, verbose_name="Công cụ?"),
                ),
                (
                    "danh_gia_chung",
                    models.TextField(blank=True, verbose_name="Nhận xét"),
                ),
                (
                    "ket_qua",
                    models.CharField(
                        choices=[
                            ("DAT", "✅ Đạt yêu cầu"),
                            ("KHONG_DAT", "❌ Không đạt"),
                        ],
                        default="DAT",
                        max_length=20,
                    ),
                ),
                (
                    "hinh_anh_tong_quan",
                    models.ImageField(
                        blank=True, null=True, upload_to="thanhtra/%Y/%m/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký Thanh tra",
                "verbose_name_plural": "3. Nhật ký Thanh tra Mobile",
                "ordering": ["-thoi_gian_den"],
            },
        ),
        migrations.CreateModel(
            name="GhiNhanTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_quet", models.DateTimeField(auto_now_add=True)),
                (
                    "lat_thuc_te",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "lng_thuc_te",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "khoang_cach",
                    models.FloatField(default=0.0, verbose_name="Lệch (m)"),
                ),
                (
                    "ket_qua",
                    models.CharField(
                        choices=[
                            ("HOP_LE", "🟢 Hợp lệ"),
                            ("CANH_BAO_XA", "🟡 Cảnh báo (Hơi xa)"),
                            ("MAT_GPS", "⚪ Mất GPS"),
                            ("GIAN_LAN", "🔴 Gian lận"),
                        ],
                        default="HOP_LE",
                        max_length=20,
                    ),
                ),
                ("toa_do", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hinh_anh_xac_thuc",
                    models.ImageField(
                        blank=True, null=True, upload_to="tuan_tra/%Y/%m/"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chi tiết quét",
                "verbose_name_plural": "Chi tiết Quét QR",
                "ordering": ["thoi_gian_quet"],
            },
        ),
        migrations.CreateModel(
            name="HangMucKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_hang_muc",
                    models.CharField(max_length=255, verbose_name="Tên hạng mục"),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Tiêu chuẩn")),
            ],
            options={
                "verbose_name_plural": "Cấu hình Hạng mục Thanh tra",
            },
        ),
        migrations.CreateModel(
            name="KetQuaKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dat_yeu_cau", models.BooleanField(default=True, verbose_name="Đạt?")),
                ("ghi_chu", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoaiTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_loai",
                    models.CharField(max_length=255, verbose_name="Tên tuyến"),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả lộ trình")),
                (
                    "thoi_gian_quy_dinh",
                    models.IntegerField(
                        default=30,
                        help_text="Thời gian tiêu chuẩn để hoàn thành tuyến",
                        verbose_name="Thời gian quy định (phút)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuyến tuần tra",
                "verbose_name_plural": "1. Cấu hình Tuyến",
                "ordering": ["muc_tieu", "ten_loai"],
            },
        ),
        migrations.CreateModel(
            name="LuotTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_bat_dau",
                    models.DateTimeField(auto_now_add=True, verbose_name="Bắt đầu"),
                ),
                (
                    "thoi_gian_ket_thuc",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kết thúc"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("DANG_DI", "⏳ Đang đi"),
                            ("HOAN_THANH", "✅ Hoàn thành"),
                            ("BO_DO", "❌ Bỏ dở"),
                        ],
                        default="DANG_DI",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt tuần tra",
                "verbose_name_plural": "2. Nhật ký Tuần tra",
                "ordering": ["-thoi_gian_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="BienBanThanhTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ket_luan",
                    models.TextField(blank=True, verbose_name="Kết luận chung"),
                ),
                (
                    "diem_danh_gia",
                    models.IntegerField(default=100, verbose_name="Điểm số"),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Mục tiêu",
                    ),
                ),
            ],
            options={
                "ordering": ["-thoi_gian"],
            },
        ),
    ]
