# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("inspection", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienbanthanhtra",
            name="thanh_tra_vien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Thanh tra viên",
            ),
        ),
        migrations.AddField(
            model_name="bienbanvipham",
            name="doi_tuong_vi_pham",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_loi_vi_pham",
                to="users.nhanvien",
                verbose_name="NV Vi phạm",
            ),
        ),
        migrations.AddField(
            model_name="bienbanvipham",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Tại mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="bienbanvipham",
            name="nguoi_lap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_bb_da_lap",
                to="users.nhanvien",
                verbose_name="Thanh tra lập",
            ),
        ),
        migrations.AddField(
            model_name="buoihuanluyen",
            name="danh_sach_tham_gia",
            field=models.ManyToManyField(
                blank=True, related_name="cac_buoi_huan_luyen", to="users.nhanvien"
            ),
        ),
        migrations.AddField(
            model_name="buoihuanluyen",
            name="nguoi_dao_tao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Giảng viên",
            ),
        ),
        migrations.AddField(
            model_name="dotthanhtra",
            name="can_bo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Cán bộ kiểm tra",
            ),
        ),
        migrations.AddField(
            model_name="dotthanhtra",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="ghinhantuantra",
            name="diem_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.diemtuantra",
                verbose_name="Điểm",
            ),
        ),
        migrations.AddField(
            model_name="ketquakiemtra",
            name="bien_ban",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet",
                to="inspection.bienbanthanhtra",
            ),
        ),
        migrations.AddField(
            model_name="ketquakiemtra",
            name="hang_muc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.hangmuckiemtra",
            ),
        ),
        migrations.AddField(
            model_name="loaituantra",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="diemtuantra",
            name="loai_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_diem",
                to="inspection.loaituantra",
                verbose_name="Thuộc tuyến",
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="loai_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.loaituantra",
                verbose_name="Tuyến đi",
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="ghinhantuantra",
            name="luot_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ghi_nhan",
                to="inspection.luottuantra",
            ),
        ),
    ]
