# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
        ("inspection", "0002_initial"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bienbanthanhtra",
            options={
                "ordering": ["-thoi_gian"],
                "verbose_name": "Biên bản thanh tra",
                "verbose_name_plural": "Biên bản thanh tra",
            },
        ),
        migrations.AlterModelOptions(
            name="buoihuanluyen",
            options={
                "ordering": ["-thoi_gian"],
                "verbose_name": "Buổi huấn luyện",
                "verbose_name_plural": "Buổi huấn luyện",
            },
        ),
        migrations.AlterModelOptions(
            name="dotthanhtra",
            options={
                "ordering": ["-thoi_gian_den"],
                "verbose_name": "Nhật ký Thanh tra Mobile",
                "verbose_name_plural": "3. Nhật ký Thanh tra Mobile",
            },
        ),
        migrations.AlterModelOptions(
            name="ghinhantuantra",
            options={
                "ordering": ["thoi_gian_quet"],
                "verbose_name": "Chi tiết quét QR",
                "verbose_name_plural": "Chi tiết Quét QR",
            },
        ),
        migrations.AlterModelOptions(
            name="hangmuckiemtra",
            options={
                "verbose_name": "Hạng mục kiểm tra",
                "verbose_name_plural": "Cấu hình Hạng mục Thanh tra",
            },
        ),
        migrations.AlterModelOptions(
            name="ketquakiemtra",
            options={
                "verbose_name": "Kết quả kiểm tra chi tiết",
                "verbose_name_plural": "Kết quả kiểm tra chi tiết",
            },
        ),
        migrations.AlterField(
            model_name="bienbanthanhtra",
            name="diem_danh_gia",
            field=models.IntegerField(default=100, verbose_name="Tổng điểm đánh giá"),
        ),
        migrations.AlterField(
            model_name="bienbanthanhtra",
            name="ket_luan",
            field=models.TextField(blank=True, verbose_name="Kết luận chung của đoàn"),
        ),
        migrations.AlterField(
            model_name="bienbanthanhtra",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Mục tiêu thanh tra",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanthanhtra",
            name="thanh_tra_vien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Thanh tra viên thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanthanhtra",
            name="thoi_gian",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Thời điểm thanh tra"
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="bang_chung_anh",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vipham/%Y/%m/",
                verbose_name="Hình ảnh bằng chứng",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ngày tạo hồ sơ"
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="doi_tuong_vi_pham",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_loi_vi_pham",
                to="users.nhanvien",
                verbose_name="Nhân viên vi phạm",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="hinh_thuc_xu_ly",
            field=models.CharField(
                choices=[
                    ("NHAC_NHO", "Nhắc nhở"),
                    ("CANH_CAO", "Cảnh cáo"),
                    ("PHAT_TIEN", "Phạt tiền (Trừ lương)"),
                    ("DINH_CHI", "Đình chỉ công tác"),
                ],
                default="PHAT_TIEN",
                max_length=20,
                verbose_name="Hình thức xử lý kỷ luật",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="loai_loi",
            field=models.CharField(
                choices=[
                    ("NGU_GAT", "😴 Ngủ gật trong ca trực"),
                    ("ROI_VI_TRI", "🏃 Rời bỏ vị trí không lý do"),
                    ("DUNG_DIEN_THOAI", "📱 Sử dụng điện thoại sai quy định"),
                    ("KHONG_DONG_PHUC", "👔 Sai quy định đồng phục/Tác phong"),
                    ("KHAC", "📝 Các lỗi vi phạm khác"),
                ],
                default="NGU_GAT",
                max_length=50,
                verbose_name="Hành vi vi phạm",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="ma_bien_ban",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Mã biên bản"
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="mo_ta",
            field=models.TextField(blank=True, verbose_name="Mô tả diễn biến chi tiết"),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Địa điểm (Mục tiêu)",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="ngay_vi_pham",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Thời điểm phát hiện vi phạm",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="nguoi_lap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_bb_da_lap",
                to="users.nhanvien",
                verbose_name="Cán bộ lập biên bản",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="so_tien_phat",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Nhập số tiền áp dụng cho hình thức Phạt tiền",
                max_digits=12,
                verbose_name="Số tiền phạt dự kiến",
            ),
        ),
        migrations.AlterField(
            model_name="bienbanvipham",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("CHO_DUYET", "⏳ Đang chờ phê duyệt"),
                    ("DA_DUYET", "✅ Đã phê duyệt xử lý"),
                    ("TU_CHOI", "❌ Đã hủy bỏ/Từ chối"),
                ],
                default="CHO_DUYET",
                max_length=20,
                verbose_name="Trạng thái hồ sơ",
            ),
        ),
        migrations.AlterField(
            model_name="buoihuanluyen",
            name="chu_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chủ đề đào tạo"
            ),
        ),
        migrations.AlterField(
            model_name="buoihuanluyen",
            name="danh_sach_tham_gia",
            field=models.ManyToManyField(
                blank=True,
                related_name="cac_buoi_huan_luyen",
                to="users.nhanvien",
                verbose_name="Danh sách nhân viên tham gia",
            ),
        ),
        migrations.AlterField(
            model_name="buoihuanluyen",
            name="dia_diem",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Địa điểm huấn luyện",
            ),
        ),
        migrations.AlterField(
            model_name="buoihuanluyen",
            name="nguoi_dao_tao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Giảng viên/Người phụ trách",
            ),
        ),
        migrations.AlterField(
            model_name="buoihuanluyen",
            name="thoi_gian",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Thời gian tổ chức"
            ),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="ban_kinh_cho_phep",
            field=models.IntegerField(
                default=50,
                help_text="Khoảng cách tối đa chấp nhận được so với tọa độ gốc",
                verbose_name="Bán kính sai lệch (m)",
            ),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="kinh_do",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Kinh độ (Longitude)",
            ),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="ma_qr",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Mã QR định danh"
            ),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="ten_diem",
            field=models.CharField(max_length=255, verbose_name="Tên điểm kiểm soát"),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="thu_tu",
            field=models.IntegerField(default=1, verbose_name="Thứ tự tuần tra"),
        ),
        migrations.AlterField(
            model_name="diemtuantra",
            name="vi_do",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Vĩ độ (Latitude)",
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="danh_gia_chung",
            field=models.TextField(blank=True, verbose_name="Nhận xét/Kiến nghị"),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="hinh_anh_tong_quan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thanhtra/%Y/%m/",
                verbose_name="Ảnh chụp tổng quan hiện trường",
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="ket_qua",
            field=models.CharField(
                choices=[
                    ("DAT", "✅ Đạt yêu cầu vận hành"),
                    ("KHONG_DAT", "❌ Không đạt yêu cầu"),
                ],
                default="DAT",
                max_length=20,
                verbose_name="Kết luận thanh tra",
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="kiem_tra_cong_cu",
            field=models.BooleanField(
                default=True, verbose_name="Kiểm tra Công cụ hỗ trợ?"
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="kiem_tra_dong_phuc",
            field=models.BooleanField(
                default=True, verbose_name="Kiểm tra Đồng phục/Tác phong?"
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="kiem_tra_so_sach",
            field=models.BooleanField(
                default=True, verbose_name="Kiểm tra Sổ sách bàn giao?"
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="quan_so_bao_cao",
            field=models.IntegerField(
                default=0, verbose_name="Quân số (Theo lịch trực)"
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="quan_so_thuc_te",
            field=models.IntegerField(
                default=0, verbose_name="Quân số (Thực tế có mặt)"
            ),
        ),
        migrations.AlterField(
            model_name="dotthanhtra",
            name="thoi_gian_den",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Thời gian bắt đầu kiểm tra",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="diem_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.diemtuantra",
                verbose_name="Điểm kiểm soát",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú nghiệp vụ"),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="hinh_anh_xac_thuc",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tuan_tra/%Y/%m/",
                verbose_name="Hình ảnh xác thực",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="ket_qua",
            field=models.CharField(
                choices=[
                    ("HOP_LE", "🟢 Hợp lệ"),
                    ("CANH_BAO_XA", "🟡 Cảnh báo (Ngoài bán kính)"),
                    ("MAT_GPS", "⚪ Không có tín hiệu GPS"),
                    ("GIAN_LAN", "🔴 Nghi vấn gian lận"),
                ],
                default="HOP_LE",
                max_length=20,
                verbose_name="Kết quả xác thực",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="khoang_cach",
            field=models.FloatField(
                default=0.0, verbose_name="Độ lệch khoảng cách (m)"
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="lat_thuc_te",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Vĩ độ thực tế",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="lng_thuc_te",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Kinh độ thực tế",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="luot_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ghi_nhan",
                to="inspection.luottuantra",
                verbose_name="Lượt tuần tra",
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="thoi_gian_quet",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời gian quét"
            ),
        ),
        migrations.AlterField(
            model_name="ghinhantuantra",
            name="toa_do",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Chuỗi tọa độ"
            ),
        ),
        migrations.AlterField(
            model_name="hangmuckiemtra",
            name="mo_ta",
            field=models.TextField(blank=True, verbose_name="Tiêu chuẩn đánh giá"),
        ),
        migrations.AlterField(
            model_name="hangmuckiemtra",
            name="ten_hang_muc",
            field=models.CharField(
                max_length=255, verbose_name="Tên hạng mục kiểm tra"
            ),
        ),
        migrations.AlterField(
            model_name="ketquakiemtra",
            name="dat_yeu_cau",
            field=models.BooleanField(default=True, verbose_name="Đạt yêu cầu?"),
        ),
        migrations.AlterField(
            model_name="ketquakiemtra",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú chi tiết"),
        ),
        migrations.AlterField(
            model_name="ketquakiemtra",
            name="hang_muc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.hangmuckiemtra",
                verbose_name="Hạng mục",
            ),
        ),
        migrations.AlterField(
            model_name="loaituantra",
            name="mo_ta",
            field=models.TextField(blank=True, verbose_name="Mô tả chi tiết lộ trình"),
        ),
        migrations.AlterField(
            model_name="loaituantra",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="loaituantra",
            name="ten_loai",
            field=models.CharField(max_length=255, verbose_name="Tên tuyến tuần tra"),
        ),
        migrations.AlterField(
            model_name="loaituantra",
            name="thoi_gian_quy_dinh",
            field=models.IntegerField(
                default=30,
                help_text="Thời gian tiêu chuẩn để hoàn thành toàn bộ tuyến tuần tra",
                verbose_name="Thời gian quy định (phút)",
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="loai_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.loaituantra",
                verbose_name="Tuyến tuần tra",
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="thoi_gian_bat_dau",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời điểm bắt đầu"
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="thoi_gian_ket_thuc",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm kết thúc"
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("DANG_DI", "⏳ Đang thực hiện"),
                    ("HOAN_THANH", "✅ Đã hoàn thành"),
                    ("BO_DO", "❌ Bỏ dở/Không hoàn thành"),
                ],
                default="DANG_DI",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
