# Generated by SCMD Pro hardening patch on 2026-06-08
from django.db import migrations, models


def dedupe_patrol_evidence(apps, schema_editor):
    """Keep the earliest evidence row before adding the DB invariant."""
    GhiNhanTuanTra = apps.get_model("inspection", "GhiNhanTuanTra")
    duplicates = (
        GhiNhanTuanTra.objects.values("luot_tuan_tra_id", "diem_tuan_tra_id")
        .annotate(total=models.Count("id"), keep_id=models.Min("id"))
        .filter(total__gt=1)
    )
    for row in duplicates:
        GhiNhanTuanTra.objects.filter(
            luot_tuan_tra_id=row["luot_tuan_tra_id"],
            diem_tuan_tra_id=row["diem_tuan_tra_id"],
        ).exclude(id=row["keep_id"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0003_alter_bienbanthanhtra_options_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_patrol_evidence, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="ghinhantuantra",
            constraint=models.UniqueConstraint(
                fields=["luot_tuan_tra", "diem_tuan_tra"],
                name="uq_patrol_evidence_once_per_checkpoint",
            ),
        ),
    ]
