# Generated by SCMD Pro hardening patch: configurable patrol GPS enforcement.
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0006_remove_dotthanhtra_insp_dtt_tenant_result_dt_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaituantra",
            name="yeu_cau_gps",
            field=models.BooleanField(
                default=False,
                help_text=_("Nếu bật, mobile phải gửi tọa độ GPS hợp lệ khi quét checkpoint."),
                verbose_name=_("Bắt buộc GPS khi tuần tra"),
            ),
        ),
    ]
