# Generated by SCMD Pro guard patrol domain correction patch v2.
from django.db import migrations, models
import django.db.models.deletion
from django.utils.translation import gettext_lazy as _


def seed_patrol_compliance_state(apps, schema_editor):
    LuotTuanTra = apps.get_model("inspection", "LuotTuanTra")
    DiemTuanTra = apps.get_model("inspection", "DiemTuanTra")
    GhiNhanTuanTra = apps.get_model("inspection", "GhiNhanTuanTra")
    for luot in LuotTuanTra.objects.all().iterator():
        required_count = DiemTuanTra.objects.filter(loai_tuan_tra_id=luot.loai_tuan_tra_id).count() if luot.loai_tuan_tra_id else 0
        evidence = GhiNhanTuanTra.objects.filter(luot_tuan_tra_id=luot.pk)
        scanned_count = evidence.values("diem_tuan_tra_id").distinct().count()
        warning_count = evidence.exclude(ket_qua="HOP_LE").count()
        if luot.trang_thai == "DANG_DI":
            compliance_state = "IN_PROGRESS"
        elif luot.trang_thai == "BO_DO":
            compliance_state = "MISSED"
        elif required_count and scanned_count >= required_count:
            compliance_state = "COMPLETED_WITH_WARNINGS" if warning_count else "COMPLETED_VALID"
        else:
            compliance_state = "MISSED"
        LuotTuanTra.objects.filter(pk=luot.pk).update(
            trang_thai_doi_soat=compliance_state,
            so_diem_bat_buoc=required_count,
            so_diem_da_quet=scanned_count,
            so_diem_canh_bao=warning_count,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_shift_change_request_applied_status"),
        ("inspection", "0007_loaituantra_yeu_cau_gps"),
    ]

    operations = [
        migrations.AddField(
            model_name="luottuantra",
            name="phan_cong_ca_truc",
            field=models.ForeignKey(
                blank=True,
                help_text=_("Phase 1 domain correction: liên kết lượt tuần tra bảo vệ với ca trực vận hành."),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="luot_tuan_tra_bao_ve",
                to="operations.phancongcatruc",
                verbose_name=_("Phân công ca trực liên quan"),
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="trang_thai_doi_soat",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", _("Đang thực hiện")),
                    ("COMPLETED_VALID", _("Hoàn thành hợp lệ")),
                    ("COMPLETED_WITH_WARNINGS", _("Hoàn thành có cảnh báo")),
                    ("MISSED", _("Bỏ lượt/thiếu điểm")),
                    ("CANCELLED_WITH_REASON", _("Đã hủy có lý do")),
                ],
                db_index=True,
                default="IN_PROGRESS",
                help_text=_("Không dùng HOAN_THANH đơn thuần để suy ra hoàn thành hợp lệ."),
                max_length=32,
                verbose_name=_("Trạng thái đối soát tuần tra"),
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="so_diem_bat_buoc",
            field=models.PositiveIntegerField(default=0, verbose_name=_("Số điểm bắt buộc")),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="so_diem_da_quet",
            field=models.PositiveIntegerField(default=0, verbose_name=_("Số điểm đã quét")),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="so_diem_canh_bao",
            field=models.PositiveIntegerField(default=0, verbose_name=_("Số điểm có cảnh báo")),
        ),
        migrations.AddIndex(
            model_name="luottuantra",
            index=models.Index(
                fields=["tenant_id", "phan_cong_ca_truc", "trang_thai_doi_soat"],
                name="insp_luot_shift_comp_idx",
            ),
        ),
        migrations.RunPython(seed_patrol_compliance_state, migrations.RunPython.noop),
    ]
