# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietPhieuNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Đơn giá nhập",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietPhieuXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "don_gia_ban",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Đơn giá (Nếu bán)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoaiVatTu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_loai", models.CharField(max_length=100, verbose_name="Tên loại")),
                (
                    "mo_ta",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
            ],
            options={
                "verbose_name": "1. Loại vật tư",
                "verbose_name_plural": "1. Loại vật tư",
            },
        ),
        migrations.CreateModel(
            name="PhieuNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_phieu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu"
                    ),
                ),
                (
                    "ngay_nhap",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày nhập"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "4. Phiếu Nhập kho",
                "verbose_name_plural": "4. Quản lý Nhập kho",
            },
        ),
        migrations.CreateModel(
            name="PhieuXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_phieu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu"
                    ),
                ),
                (
                    "loai_xuat",
                    models.CharField(
                        choices=[
                            ("CAP_PHAT", "Cấp phát (Miễn phí/Định mức)"),
                            ("BAN_TRU_LUONG", "Bán (Trừ vào lương tháng)"),
                            ("CONG_CU", "Cấp CCHT cho Mục tiêu (Không thu tiền)"),
                            ("HUY", "Xuất hủy/Thanh lý"),
                        ],
                        default="CAP_PHAT",
                        max_length=20,
                        verbose_name="Loại xuất",
                    ),
                ),
                (
                    "trang_thai_thanh_toan",
                    models.CharField(
                        choices=[
                            ("KHONG_AP_DUNG", "Không áp dụng"),
                            ("CHUA_TRU", "Chưa trừ lương"),
                            ("DA_TRU", "Đã trừ lương"),
                        ],
                        default="KHONG_AP_DUNG",
                        max_length=20,
                        verbose_name="Trạng thái thanh toán",
                    ),
                ),
                (
                    "ngay_xuat",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày xuất"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "tong_tien_phai_thu",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Tổng tiền phải thu",
                    ),
                ),
            ],
            options={
                "verbose_name": "5. Phiếu Xuất kho",
                "verbose_name_plural": "5. Quản lý Xuất kho",
            },
        ),
        migrations.CreateModel(
            name="VatTu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_vat_tu",
                    models.CharField(max_length=200, verbose_name="Tên vật tư"),
                ),
                (
                    "don_vi_tinh",
                    models.CharField(default="Cái", max_length=50, verbose_name="ĐVT"),
                ),
                (
                    "gia_nhap",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Giá nhập (Vốn)",
                    ),
                ),
                (
                    "gia_ban",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Giá áp dụng khi nhân viên mua thêm/làm mất",
                        max_digits=12,
                        verbose_name="Giá bán/Trừ lương",
                    ),
                ),
                (
                    "so_luong_ton",
                    models.IntegerField(default=0, verbose_name="Tồn kho tổng"),
                ),
                (
                    "hinh_anh",
                    models.ImageField(blank=True, null=True, upload_to="vattu/"),
                ),
                (
                    "muc_canh_bao",
                    models.IntegerField(
                        default=10, verbose_name="Mức cảnh báo tồn thấp"
                    ),
                ),
            ],
            options={
                "verbose_name": "2. Vật tư & CCHT",
                "verbose_name_plural": "2. Kho Tổng",
            },
        ),
        migrations.CreateModel(
            name="CongCuTaiMucTieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong_dang_giu",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng đang giữ"
                    ),
                ),
                ("ngay_cap_gan_nhat", models.DateField(auto_now=True)),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.muctieu",
                        verbose_name="Mục tiêu",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. Công cụ tại Mục tiêu",
                "verbose_name_plural": "3. Công cụ tại Mục tiêu",
            },
        ),
    ]
