# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phieunhap",
            name="nguoi_nhap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Thủ kho nhập",
            ),
        ),
        migrations.AddField(
            model_name="chitietphieunhap",
            name="phieu_nhap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet",
                to="inventory.phieunhap",
            ),
        ),
        migrations.AddField(
            model_name="phieuxuat",
            name="muc_tieu_nhan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Mục tiêu nhận (CCHT)",
            ),
        ),
        migrations.AddField(
            model_name="phieuxuat",
            name="nhan_vien_nhan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Nhân viên nhận",
            ),
        ),
        migrations.AddField(
            model_name="chitietphieuxuat",
            name="phieu_xuat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet",
                to="inventory.phieuxuat",
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="loai_vat_tu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.loaivattu",
                verbose_name="Loại",
            ),
        ),
        migrations.AddField(
            model_name="congcutaimuctieu",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Công cụ",
            ),
        ),
        migrations.AddField(
            model_name="chitietphieuxuat",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư",
            ),
        ),
        migrations.AddField(
            model_name="chitietphieunhap",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="congcutaimuctieu",
            unique_together={("muc_tieu", "vat_tu")},
        ),
    ]
