# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
        ("inventory", "0002_initial"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chitietphieunhap",
            options={
                "verbose_name": "Chi tiết phiếu nhập",
                "verbose_name_plural": "Chi tiết phiếu nhập",
            },
        ),
        migrations.AlterModelOptions(
            name="chitietphieuxuat",
            options={
                "verbose_name": "Chi tiết phiếu xuất",
                "verbose_name_plural": "Chi tiết phiếu xuất",
            },
        ),
        migrations.AlterField(
            model_name="chitietphieunhap",
            name="don_gia",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Đơn giá nhập thực tế",
            ),
        ),
        migrations.AlterField(
            model_name="chitietphieunhap",
            name="so_luong",
            field=models.PositiveIntegerField(verbose_name="Số lượng nhập"),
        ),
        migrations.AlterField(
            model_name="chitietphieuxuat",
            name="don_gia_ban",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Đơn giá áp dụng",
            ),
        ),
        migrations.AlterField(
            model_name="chitietphieuxuat",
            name="so_luong",
            field=models.PositiveIntegerField(verbose_name="Số lượng xuất"),
        ),
        migrations.AlterField(
            model_name="chitietphieuxuat",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư/CCHT",
            ),
        ),
        migrations.AlterField(
            model_name="congcutaimuctieu",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="congcutaimuctieu",
            name="ngay_cap_gan_nhat",
            field=models.DateField(
                auto_now=True, verbose_name="Ngày cập nhật gần nhất"
            ),
        ),
        migrations.AlterField(
            model_name="congcutaimuctieu",
            name="so_luong_dang_giu",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số lượng thực tế tại MT"
            ),
        ),
        migrations.AlterField(
            model_name="congcutaimuctieu",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Tên công cụ",
            ),
        ),
        migrations.AlterField(
            model_name="loaivattu",
            name="mo_ta",
            field=models.TextField(
                blank=True, default="", verbose_name="Mô tả danh mục"
            ),
        ),
        migrations.AlterField(
            model_name="loaivattu",
            name="ten_loai",
            field=models.CharField(max_length=100, verbose_name="Tên loại vật tư"),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú nhập"),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="ma_phieu",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Mã số phiếu nhập"
            ),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="ngay_nhap",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày giờ nhập kho"
            ),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="nguoi_nhap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Thủ kho thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú xuất"),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="loai_xuat",
            field=models.CharField(
                choices=[
                    ("CAP_PHAT", "Cấp phát (Miễn phí/Định mức)"),
                    ("BAN_TRU_LUONG", "Bán (Khấu trừ vào lương tháng)"),
                    ("CONG_CU", "Cấp CCHT cho Mục tiêu (Không thu tiền)"),
                    ("HUY", "Xuất hủy/Thanh lý tài sản"),
                ],
                default="CAP_PHAT",
                max_length=20,
                verbose_name="Hình thức xuất",
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="ma_phieu",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Mã số phiếu xuất"
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="muc_tieu_nhan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Mục tiêu tiếp nhận (CCHT)",
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="ngay_xuat",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày giờ xuất kho"
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="nhan_vien_nhan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Nhân viên tiếp nhận",
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="tong_tien_phai_thu",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                editable=False,
                max_digits=15,
                verbose_name="Tổng tiền khấu trừ",
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="trang_thai_thanh_toan",
            field=models.CharField(
                choices=[
                    ("KHONG_AP_DUNG", "Không áp dụng"),
                    ("CHUA_TRU", "Chờ khấu trừ lương"),
                    ("DA_TRU", "Đã hoàn tất trừ lương"),
                ],
                default="KHONG_AP_DUNG",
                max_length=20,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="don_vi_tinh",
            field=models.CharField(
                default="Cái", max_length=50, verbose_name="Đơn vị tính"
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="gia_ban",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Giá áp dụng khi nhân viên mua thêm hoặc làm mất/hư hỏng",
                max_digits=12,
                verbose_name="Giá bán/Trừ lương",
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="gia_nhap",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Giá vốn (Nhập)",
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="hinh_anh",
            field=models.ImageField(
                blank=True, null=True, upload_to="vattu/", verbose_name="Ảnh minh họa"
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="loai_vat_tu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.loaivattu",
                verbose_name="Nhóm vật tư",
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="muc_canh_bao",
            field=models.IntegerField(
                default=10, verbose_name="Mức cảnh báo tồn tối thiểu"
            ),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="so_luong_ton",
            field=models.IntegerField(default=0, verbose_name="Tồn kho hiện tại"),
        ),
        migrations.AlterField(
            model_name="vattu",
            name="ten_vat_tu",
            field=models.CharField(max_length=200, verbose_name="Tên vật tư/CCHT"),
        ),
    ]
