# Generated by Django 5.2.5 on 2026-06-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_muctieudongiahistory'),
        ('inventory', '0007_inventory_ledger_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphieunhap',
            name='vat_tu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vattu', verbose_name='Vật tư'),
        ),
        migrations.AlterField(
            model_name='chitietphieuxuat',
            name='vat_tu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vattu', verbose_name='Vật tư/CCHT'),
        ),
        migrations.AlterField(
            model_name='congcutaimuctieu',
            name='muc_tieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.muctieu', verbose_name='Mục tiêu bảo vệ'),
        ),
        migrations.AlterField(
            model_name='congcutaimuctieu',
            name='vat_tu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vattu', verbose_name='Tên công cụ'),
        ),
    ]
