# Generated by SCMD Pro Phase F asset recovery patch.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import core.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0014_payroll_phase_b_records"),
        ("users", "0013_hr_phase_b_records"),
        ("inventory", "0011_rename_inventory_v_tenant_835dd7_idx_inventory_v_tenant__776506_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhieuThuHoi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("ma_phieu", models.CharField(db_index=True, max_length=64, verbose_name="Mã phiếu thu hồi")),
                ("ngay_thu_hoi", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Ngày thu hồi")),
                ("file_bien_ban", models.FileField(blank=True, null=True, upload_to="phieu_thu_hoi/%Y/%m/", verbose_name="File biên bản")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("POSTED", "Đã ghi sổ"), ("VOIDED", "Đã hủy")], db_index=True, default="DRAFT", max_length=20, verbose_name="Trạng thái")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm ghi sổ")),
                ("voided_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm hủy")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_phieu_thu_hoi_tai_san", to="users.nhanvien", verbose_name="Nhân viên bàn giao")),
                ("nguoi_thu_hoi", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phieu_da_thu_hoi", to="users.nhanvien", verbose_name="Người thu hồi")),
                ("offboarding_checklist", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phieu_thu_hoi_tai_san", to="users.offboardingchecklist", verbose_name="Checklist offboarding")),
                ("quyet_dinh_nghi_viec", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_phieu_thu_hoi_tai_san", to="users.quyetdinhnghiviec", verbose_name="Quyết định nghỉ việc")),
            ],
            options={
                "verbose_name": "7. Phiếu thu hồi tài sản",
                "verbose_name_plural": "7. Phiếu thu hồi tài sản",
                "ordering": ["-ngay_thu_hoi", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChiTietPhieuThuHoi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_luong_thu_hoi", models.PositiveIntegerField(default=0, verbose_name="Số lượng thu hồi")),
                ("so_luong_nhap_lai_kho", models.PositiveIntegerField(default=0, verbose_name="Số lượng nhập lại kho")),
                ("so_luong_mat_hong", models.PositiveIntegerField(default=0, verbose_name="Số lượng mất/hỏng/thiếu")),
                ("tinh_trang", models.CharField(choices=[("TOT", "Tốt"), ("HAO_MON", "Hao mòn"), ("HONG", "Hỏng"), ("MAT", "Mất"), ("THIEU", "Thiếu")], db_index=True, default="TOT", max_length=20, verbose_name="Tình trạng")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("chi_tiet_phieu_xuat", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_dong_thu_hoi", to="inventory.chitietphieuxuat", verbose_name="Dòng phiếu xuất gốc")),
                ("phieu_thu_hoi", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chi_tiet", to="inventory.phieuthuhoi", verbose_name="Phiếu thu hồi")),
                ("vat_tu", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.vattu", verbose_name="Vật tư")),
            ],
            options={
                "verbose_name": "Chi tiết phiếu thu hồi",
                "verbose_name_plural": "Chi tiết phiếu thu hồi",
            },
        ),
        migrations.CreateModel(
            name="BienBanMatHongVatTu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng mất/hỏng/thiếu")),
                ("don_gia_khau_tru", models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Đơn giá khấu trừ")),
                ("tong_tien", models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=14, verbose_name="Tổng tiền khấu trừ")),
                ("ly_do", models.TextField(blank=True, verbose_name="Lý do")),
                ("file_minh_chung", models.FileField(blank=True, null=True, upload_to="bien_ban_mat_hong/%Y/%m/", verbose_name="File minh chứng")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("APPLIED", "Đã áp dụng khấu trừ"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("chi_tiet_thu_hoi", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_bien_ban_mat_hong", to="inventory.chitietphieuthuhoi", verbose_name="Dòng thu hồi")),
                ("khoan_khau_tru", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_bien_ban_mat_hong_vat_tu", to="accounting.khoankhautrunhanvien", verbose_name="Khoản khấu trừ liên quan")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_bien_ban_mat_hong_vat_tu", to="users.nhanvien", verbose_name="Nhân viên chịu trách nhiệm")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_bien_ban_mat_hong_vat_tu_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("phieu_thu_hoi", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_bien_ban_mat_hong", to="inventory.phieuthuhoi", verbose_name="Phiếu thu hồi")),
                ("vat_tu", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cac_bien_ban_mat_hong", to="inventory.vattu", verbose_name="Vật tư")),
            ],
            options={
                "verbose_name": "8. Biên bản mất/hỏng vật tư",
                "verbose_name_plural": "8. Biên bản mất/hỏng vật tư",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="inventoryledgerentry",
            name="document_type",
            field=models.CharField(choices=[("RECEIPT", "Phiếu nhập"), ("ISSUE", "Phiếu xuất"), ("RECOVERY", "Phiếu thu hồi")], max_length=20),
        ),
        migrations.AddField(
            model_name="inventoryledgerentry",
            name="phieu_thu_hoi",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="inventory.phieuthuhoi", verbose_name="Phiếu thu hồi liên quan"),
        ),
        migrations.AddField(
            model_name="inventoryledgerentry",
            name="chi_tiet_phieu_thu_hoi",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="inventory.chitietphieuthuhoi", verbose_name="Chi tiết phiếu thu hồi liên quan"),
        ),
        migrations.AddIndex(model_name="phieuthuhoi", index=models.Index(fields=["tenant_id", "trang_thai", "ngay_thu_hoi"], name="inv_rec_tenant_state_dt_idx")),
        migrations.AddIndex(model_name="phieuthuhoi", index=models.Index(fields=["tenant_id", "nhan_vien", "trang_thai"], name="inv_rec_tenant_staff_st_idx")),
        migrations.AddConstraint(model_name="phieuthuhoi", constraint=models.UniqueConstraint(fields=("tenant_id", "ma_phieu"), name="uq_inv_recovery_tenant_code")),
        migrations.AddIndex(model_name="chitietphieuthuhoi", index=models.Index(fields=["tenant_id", "chi_tiet_phieu_xuat"], name="inv_recl_tenant_issue_idx")),
        migrations.AddIndex(model_name="chitietphieuthuhoi", index=models.Index(fields=["tenant_id", "vat_tu", "tinh_trang"], name="inv_recl_tenant_vt_cond_idx")),
        migrations.AddIndex(model_name="bienbanmathongvattu", index=models.Index(fields=["tenant_id", "trang_thai", "created_at"], name="inv_dmg_tenant_stat_cr_idx")),
        migrations.AddIndex(model_name="bienbanmathongvattu", index=models.Index(fields=["tenant_id", "nhan_vien", "trang_thai"], name="inv_dmg_tenant_staff_st_idx")),
        migrations.AddIndex(model_name="inventoryledgerentry", index=models.Index(fields=["phieu_thu_hoi", "-created_at"], name="inv_led_rec_cr_idx")),
        migrations.AddConstraint(model_name="inventoryledgerentry", constraint=models.UniqueConstraint(condition=models.Q(("chi_tiet_phieu_thu_hoi__isnull", False)), fields=("chi_tiet_phieu_thu_hoi", "movement_type"), name="inventory_ledger_unique_recovery_detail_movement")),
    ]
