# Generated by Django 5.2.5 on 2026-03-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baocao",
            options={
                "managed": False,
                "verbose_name": "Trung tâm Báo cáo & Thống kê",
                "verbose_name_plural": "6. Báo cáo & Thống kê",
            },
        ),
    ]
