# Generated by Django 5.2.5 on 2026-03-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_baocao_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="baocao",
            table="virtual_reports_anchor",
        ),
    ]
