# file: nginx/default.conf

upstream scmd_backend {
    server web:8000;
}

server {
    listen 80;
    server_name localhost; # Hoặc tên miền của bạn (vd: scmd.vn)

    # 1. Phục vụ Static Files (Siêu tốc)
    location /static/ {
        alias /app/staticfiles/;
    }

    # 2. Phục vụ Media Files (Ảnh upload)
    location /media/ {
        alias /app/media/;
    }

    # 3. Chuyển tiếp request vào Django (Daphne)
    location / {
        proxy_pass http://scmd_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        
        # Cấu hình quan trọng cho WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    # Tăng giới hạn upload file (vd: 20MB cho ảnh báo cáo)
    client_max_body_size 20M;
}