# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaoCaoDeXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_de_xuat",
                    models.CharField(
                        choices=[
                            ("VATTU", "Xin cấp vật tư/VPP"),
                            ("DONGPHUC", "Xin cấp đồng phục"),
                            ("DOICA", "Xin đổi ca trực"),
                            ("NGHIPHEP", "Xin nghỉ phép"),
                            ("KHAC", "Đề xuất khác"),
                        ],
                        default="KHAC",
                        max_length=20,
                        verbose_name="Loại đề xuất",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="de_xuat/%Y/%m/",
                        verbose_name="Ảnh đính kèm",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("CHO_CH", "Chờ Chỉ huy duyệt"),
                            ("CHO_NV", "Chờ P.Nghiệp vụ duyệt"),
                            ("DUYET", "Đã duyệt (Chấp thuận)"),
                            ("TUCHOI", "Đã từ chối"),
                            ("VP", "Chuyển Văn phòng (Vượt thẩm quyền)"),
                        ],
                        default="CHO_CH",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "ngay_gui",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Ngày gửi",
                    ),
                ),
                (
                    "y_kien_chi_huy",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ý kiến chỉ huy"
                    ),
                ),
                (
                    "thoi_gian_chi_huy_duyet",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "y_kien_nghiep_vu",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ý kiến nghiệp vụ"
                    ),
                ),
                (
                    "thoi_gian_nghiep_vu_duyet",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Đề xuất Nghiệp vụ",
                "verbose_name_plural": "Danh sách Đề xuất",
                "ordering": ["-ngay_gui"],
            },
        ),
        migrations.CreateModel(
            name="BaoCaoSuCo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                (
                    "ma_su_co",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "thoi_gian_phat_hien",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Thời gian phát hiện",
                    ),
                ),
                (
                    "mo_ta_chi_tiet",
                    models.TextField(default="", verbose_name="Mô tả chi tiết"),
                ),
                (
                    "hinh_anh_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="su_co/%Y/%m/",
                        verbose_name="Ảnh hiện trường 1",
                    ),
                ),
                (
                    "hinh_anh_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="su_co/%Y/%m/",
                        verbose_name="Ảnh hiện trường 2",
                    ),
                ),
                (
                    "file_ghi_am",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="su_co/audio/%Y/%m/",
                        verbose_name="File ghi âm (Voice)",
                    ),
                ),
                (
                    "muc_do",
                    models.CharField(
                        choices=[
                            ("THAP", "Thấp"),
                            ("TB", "Trung bình"),
                            ("CAO", "Cao"),
                            ("NGUY_HIEM", "Nguy hiểm"),
                        ],
                        db_index=True,
                        default="TB",
                        max_length=20,
                        verbose_name="Mức độ nghiêm trọng",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("CHO_XU_LY", "Chờ xử lý"),
                            ("DANG_XU_LY", "Đang xử lý"),
                            ("DA_XU_LY", "Đã xử lý (Không đền bù)"),
                            ("CHO_DEN_BU", "Chờ đền bù (Có thiệt hại)"),
                            ("HOAN_TAT", "Hoàn tất (Đã trừ lương/Đền bù xong)"),
                            ("HUY", "Hủy bỏ"),
                        ],
                        db_index=True,
                        default="CHO_XU_LY",
                        max_length=20,
                        verbose_name="Trạng thái xử lý",
                    ),
                ),
                (
                    "tong_thiet_hai",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng giá trị thiệt hại",
                    ),
                ),
                (
                    "cong_ty_chi_tra",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Số tiền công ty bỏ ra đền cho khách",
                        max_digits=15,
                        verbose_name="Công ty chịu",
                    ),
                ),
                (
                    "phai_thu_nhan_vien",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Nhập số tiền sẽ trừ vào lương nhân viên gây lỗi",
                        max_digits=15,
                        verbose_name="Số tiền phải thu NV",
                    ),
                ),
                (
                    "ghi_chu_quan_ly",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú/Phương án xử lý"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Báo cáo sự cố",
                "verbose_name_plural": "Danh sách sự cố",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaLamViec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_ca", models.CharField(max_length=100, verbose_name="Tên ca")),
                ("gio_bat_dau", models.TimeField(verbose_name="Giờ bắt đầu")),
                ("gio_ket_thuc", models.TimeField(verbose_name="Giờ kết thúc")),
            ],
            options={
                "verbose_name": "Ca làm việc",
                "verbose_name_plural": "Danh sách Ca làm việc",
                "ordering": ["gio_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="ChamCong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_check_in",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Thời gian Check-in",
                    ),
                ),
                (
                    "thoi_gian_check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian Check-out"
                    ),
                ),
                (
                    "anh_check_in",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="check_in/%Y/%m/",
                        verbose_name="Ảnh Check-in",
                    ),
                ),
                (
                    "anh_check_out",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="check_out/%Y/%m/",
                        verbose_name="Ảnh Check-out",
                    ),
                ),
                (
                    "lat_check_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Vĩ độ In",
                    ),
                ),
                (
                    "long_check_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kinh độ In",
                    ),
                ),
                (
                    "lat_check_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Vĩ độ Out",
                    ),
                ),
                (
                    "long_check_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kinh độ Out",
                    ),
                ),
                (
                    "ip_check_in",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Check-in"
                    ),
                ),
                (
                    "ip_check_out",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Check-out"
                    ),
                ),
                (
                    "thiet_bi_check_in",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thiết bị Check-in",
                    ),
                ),
                (
                    "thiet_bi_check_out",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thiết bị Check-out",
                    ),
                ),
                (
                    "vi_tri_hop_le",
                    models.BooleanField(
                        default=True,
                        help_text="False nếu Check-in quá xa mục tiêu",
                        verbose_name="Đúng vị trí?",
                    ),
                ),
                (
                    "khoang_cach_check_in",
                    models.FloatField(
                        default=0.0,
                        help_text="Khoảng cách thực tế tới tâm mục tiêu",
                        verbose_name="Khoảng cách (m)",
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Dữ liệu Chấm công",
                "verbose_name_plural": "Dữ liệu Chấm công",
            },
        ),
        migrations.CreateModel(
            name="KiemTraQuanSo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_gui_yeu_cau",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian gọi"
                    ),
                ),
                (
                    "thoi_gian_phan_hoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian trả lời"
                    ),
                ),
                (
                    "anh_xac_thuc",
                    models.ImageField(
                        blank=True, null=True, upload_to="alive_check/%Y/%m/"
                    ),
                ),
                (
                    "toa_do_xac_thuc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ phản hồi"),
                            ("OK", "Đã xác nhận"),
                            ("MISSED", "Bỏ lỡ"),
                            ("LATE", "Phản hồi muộn"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kiểm tra quân số",
                "verbose_name_plural": "Lịch sử Alive Check",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhanCongCaTruc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ngay_truc",
                    models.DateField(db_index=True, verbose_name="Ngày trực"),
                ),
            ],
            options={
                "verbose_name": "Phân công ca trực",
                "verbose_name_plural": "Bảng Phân công ca trực",
                "ordering": ["ngay_truc", "ca_lam_viec__gio_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="ViTriChot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_vi_tri",
                    models.CharField(max_length=255, verbose_name="Tên vị trí"),
                ),
            ],
            options={
                "verbose_name": "Vị trí chốt",
                "verbose_name_plural": "Danh sách Vị trí chốt",
            },
        ),
    ]
