# Generated by Django 4.x on 2026-05-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('users', '0002_update_related_names'),
        ('clients', '0002_update_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrichot',
            name='muc_tieu',
            field=models.ForeignKey(help_text='Chọn khách hàng/mục tiêu quản lý vị trí trực này', on_delete=django.db.models.deletion.CASCADE, related_name='cac_vi_tri_chot', to='clients.muctieu', verbose_name='Mục tiêu bảo vệ'),
        ),
        migrations.AlterField(
            model_name='phancongcatruc',
            name='ca_lam_viec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_phan_cong', to='operations.calamviec', verbose_name='Ca trực'),
        ),
        migrations.AlterField(
            model_name='phancongcatruc',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_phan_cong', to='users.nhanvien', verbose_name='Nhân viên thực hiện'),
        ),
        migrations.AlterField(
            model_name='phancongcatruc',
            name='vi_tri_chot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_phan_cong', to='operations.vitrichot', verbose_name='Vị trí chốt'),
        ),
        migrations.AlterField(
            model_name='baocaodexuat',
            name='chi_huy_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_de_xuat_chi_huy_duyet', to='users.nhanvien', verbose_name='Chỉ huy duyệt'),
        ),
        migrations.AlterField(
            model_name='baocaodexuat',
            name='nguoi_duyet_nghiep_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_de_xuat_nghiep_vu_duyet', to='users.nhanvien', verbose_name='Nghiệp vụ duyệt'),
        ),
    ]