# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("operations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baocaodexuat",
            name="chi_huy_duyet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="de_xuat_chi_huy_duyet",
                to="users.nhanvien",
                verbose_name="Chỉ huy duyệt",
            ),
        ),
        migrations.AddField(
            model_name="baocaodexuat",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Tại mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="baocaodexuat",
            name="nguoi_duyet_nghiep_vu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="de_xuat_nghiep_vu_duyet",
                to="users.nhanvien",
                verbose_name="Nghiệp vụ duyệt",
            ),
        ),
        migrations.AddField(
            model_name="baocaodexuat",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Người gửi",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Tại mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="nguoi_xu_ly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co_phai_xu_ly",
                to="users.nhanvien",
                verbose_name="Cán bộ xử lý hồ sơ",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="nhan_vien_bao_cao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_su_co_da_bao",
                to="users.nhanvien",
                verbose_name="Người báo cáo (Nhân chứng)",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="nhan_vien_co_loi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co_gay_ra",
                to="users.nhanvien",
                verbose_name="Nhân viên gây lỗi (Bị trừ lương)",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="ca_lam_viec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.calamviec",
                verbose_name="Ca làm việc",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="kiemtraquanso",
            name="ca_truc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_lan_kiem_tra",
                to="operations.phancongcatruc",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="ca_truc",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chamcong",
                to="operations.phancongcatruc",
                verbose_name="Ca trực",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="ca_truc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.phancongcatruc",
                verbose_name="Ca trực liên quan",
            ),
        ),
        migrations.AddField(
            model_name="vitrichot",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vi_tri_chot",
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="vi_tri_chot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.vitrichot",
                verbose_name="Vị trí chốt",
            ),
        ),
        migrations.AddIndex(
            model_name="phancongcatruc",
            index=models.Index(
                fields=["nhan_vien", "ngay_truc"], name="operations__nhan_vi_569674_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phancongcatruc",
            index=models.Index(
                fields=["vi_tri_chot", "ngay_truc"],
                name="operations__vi_tri__1e8a67_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phancongcatruc",
            unique_together={("nhan_vien", "ngay_truc", "ca_lam_viec")},
        ),
    ]
