# Generated by Django 5.2.5 on 2025-12-10 05:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chamcong",
            name="lat_check_in",
        ),
        migrations.RemoveField(
            model_name="chamcong",
            name="lat_check_out",
        ),
        migrations.RemoveField(
            model_name="chamcong",
            name="long_check_in",
        ),
        migrations.RemoveField(
            model_name="chamcong",
            name="long_check_out",
        ),
        migrations.AddField(
            model_name="chamcong",
            name="location_check_in",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
                verbose_name="Vị trí In",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="location_check_out",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
                verbose_name="Vị trí Out",
            ),
        ),
    ]
