# Generated by Django 5.2.5 on 2026-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_remove_chamcong_lat_check_in_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chamcong",
            options={
                "ordering": ["-thoi_gian_check_in"],
                "verbose_name": "Dữ liệu Chấm công",
                "verbose_name_plural": "Dữ liệu Chấm công",
            },
        ),
        migrations.AddField(
            model_name="chamcong",
            name="is_mock_location",
            field=models.BooleanField(
                default=False,
                help_text="Phát hiện sử dụng Fake GPS",
                verbose_name="Giả lập GPS?",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="khoang_cach_check_out",
            field=models.FloatField(default=0.0, verbose_name="Khoảng cách Out (m)"),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="khoang_cach_check_in",
            field=models.FloatField(default=0.0, verbose_name="Khoảng cách (m)"),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="vi_tri_hop_le",
            field=models.BooleanField(default=True, verbose_name="Đúng vị trí?"),
        ),
    ]
