# Generated by Django 5.2.5 on 2026-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0004_alter_chamcong_options_chamcong_is_mock_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chamcong",
            options={
                "verbose_name": "Dữ liệu Chấm công",
                "verbose_name_plural": "Dữ liệu Chấm công",
            },
        ),
        migrations.RemoveField(
            model_name="chamcong",
            name="is_mock_location",
        ),
        migrations.RemoveField(
            model_name="chamcong",
            name="khoang_cach_check_out",
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="khoang_cach_check_in",
            field=models.FloatField(
                default=0.0,
                help_text="Khoảng cách thực tế tới tâm mục tiêu",
                verbose_name="Khoảng cách (m)",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="vi_tri_hop_le",
            field=models.BooleanField(
                default=True,
                help_text="False nếu Check-in quá xa mục tiêu",
                verbose_name="Đúng vị trí?",
            ),
        ),
    ]
