# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
        ("operations", "0005_alter_chamcong_options_and_more"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baocaodexuat",
            options={
                "ordering": ["-ngay_gui"],
                "verbose_name": "Đề xuất nghiệp vụ",
                "verbose_name_plural": "6. Danh sách Đề xuất",
            },
        ),
        migrations.AlterModelOptions(
            name="baocaosuco",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Báo cáo sự cố",
                "verbose_name_plural": "5. Danh sách sự cố",
            },
        ),
        migrations.AlterModelOptions(
            name="calamviec",
            options={
                "ordering": ["gio_bat_dau"],
                "verbose_name": "Ca làm việc",
                "verbose_name_plural": "2. Danh sách Ca làm việc",
            },
        ),
        migrations.AlterModelOptions(
            name="chamcong",
            options={
                "verbose_name": "Dữ liệu Chấm công",
                "verbose_name_plural": "4. Dữ liệu Chấm công",
            },
        ),
        migrations.AlterModelOptions(
            name="kiemtraquanso",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kiểm tra quân số",
                "verbose_name_plural": "7. Lịch sử Alive Check",
            },
        ),
        migrations.AlterModelOptions(
            name="phancongcatruc",
            options={
                "ordering": ["ngay_truc", "ca_lam_viec__gio_bat_dau"],
                "verbose_name": "Phân công ca trực",
                "verbose_name_plural": "3. Bảng Phân công ca trực",
            },
        ),
        migrations.AlterModelOptions(
            name="vitrichot",
            options={
                "verbose_name": "Vị trí chốt trực",
                "verbose_name_plural": "1. Danh sách Vị trí chốt",
            },
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="hinh_anh",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="de_xuat/%Y/%m/",
                verbose_name="Hình ảnh/Tài liệu đính kèm",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="loai_de_xuat",
            field=models.CharField(
                choices=[
                    ("VATTU", "Xin cấp vật tư/Văn phòng phẩm"),
                    ("DONGPHUC", "Xin cấp mới/đổi đồng phục"),
                    ("DOICA", "Xin đổi ca trực/Tăng ca"),
                    ("NGHIPHEP", "Xin nghỉ phép/Nghỉ chế độ"),
                    ("KHAC", "Các đề xuất khác"),
                ],
                default="KHAC",
                max_length=20,
                verbose_name="Loại đề xuất",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="ngay_gui",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Ngày gửi đề xuất",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên đề xuất",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="noi_dung",
            field=models.TextField(verbose_name="Nội dung trình bày chi tiết"),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="thoi_gian_chi_huy_duyet",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm CH duyệt"
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="thoi_gian_nghiep_vu_duyet",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm NV duyệt"
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="tieu_de",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề ngắn gọn"),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("CHO_CH", "⏳ Chờ Chỉ huy mục tiêu duyệt"),
                    ("CHO_NV", "🛡️ Chờ Phòng Nghiệp vụ duyệt"),
                    ("DUYET", "✅ Đã chấp thuận"),
                    ("TUCHOI", "❌ Đã từ chối"),
                    ("VP", "🏢 Vượt thẩm quyền - Chuyển Văn phòng"),
                ],
                default="CHO_CH",
                max_length=20,
                verbose_name="Trạng thái phê duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="y_kien_chi_huy",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ý kiến của Chỉ huy"
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="y_kien_nghiep_vu",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ý kiến của Phòng nghiệp vụ"
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="ca_truc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.phancongcatruc",
                verbose_name="Phiên trực liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="cong_ty_chi_tra",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Số tiền công ty hỗ trợ đền bù cho khách hàng",
                max_digits=15,
                verbose_name="Công ty chi trả",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="ghi_chu_quan_ly",
            field=models.TextField(
                blank=True, null=True, verbose_name="Phương án/Kết quả xử lý"
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="ma_su_co",
            field=models.CharField(
                blank=True,
                default="PENDING",
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Mã vụ việc",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="mo_ta_chi_tiet",
            field=models.TextField(
                default="",
                help_text="Tường trình diễn biến từ lúc phát hiện đến lúc xử lý",
                verbose_name="Diễn biến chi tiết",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="muc_do",
            field=models.CharField(
                choices=[
                    ("THAP", "Thấp (Nhắc nhở)"),
                    ("TB", "Trung bình (Lập biên bản)"),
                    ("CAO", "Cao (Thiệt hại tài sản)"),
                    ("NGUY_HIEM", "Nguy hiểm (Đe dọa tính mạng/An ninh)"),
                ],
                db_index=True,
                default="TB",
                max_length=20,
                verbose_name="Mức độ nghiêm trọng",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Địa điểm (Mục tiêu)",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="nguoi_xu_ly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co_phai_xu_ly",
                to="users.nhanvien",
                verbose_name="Cán bộ thụ lý",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="nhan_vien_bao_cao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_su_co_da_bao",
                to="users.nhanvien",
                verbose_name="Người phát hiện",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="nhan_vien_co_loi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co_gay_ra",
                to="users.nhanvien",
                verbose_name="Nhân viên gây lỗi",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="phai_thu_nhan_vien",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Khoản khấu trừ lương nhân viên gây lỗi",
                max_digits=15,
                verbose_name="Số tiền trừ lương NV",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="tieu_de",
            field=models.CharField(
                help_text="Tóm tắt ngắn gọn sự việc xảy ra",
                max_length=200,
                verbose_name="Tiêu đề sự cố",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("CHO_XU_LY", "⏳ Chờ xử lý"),
                    ("DANG_XU_LY", "🔄 Đang xử lý"),
                    ("DA_XU_LY", "✅ Đã xử lý (Không đền bù)"),
                    ("CHO_DEN_BU", "💸 Chờ đền bù (Có thiệt hại)"),
                    ("HOAN_TAT", "🏁 Hoàn tất xử lý"),
                    ("HUY", "❌ Đã hủy bỏ"),
                ],
                db_index=True,
                default="CHO_XU_LY",
                max_length=20,
                verbose_name="Trạng thái hồ sơ",
            ),
        ),
        migrations.AlterField(
            model_name="calamviec",
            name="ten_ca",
            field=models.CharField(
                help_text="VD: Ca 1 (06h-18h), Ca hành chính",
                max_length=100,
                verbose_name="Tên ca trực",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="anh_check_in",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="check_in/%Y/%m/",
                verbose_name="Ảnh xác thực In",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="anh_check_out",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="check_out/%Y/%m/",
                verbose_name="Ảnh xác thực Out",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="ca_truc",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chamcong",
                to="operations.phancongcatruc",
                verbose_name="Phiên trực liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú chấm công"),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="ip_check_in",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP nguồn In"
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="ip_check_out",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP nguồn Out"
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="khoang_cach_check_in",
            field=models.FloatField(
                default=0.0,
                help_text="Khoảng cách từ nhân viên đến tâm mục tiêu (mét)",
                verbose_name="Độ lệch khoảng cách (m)",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="location_check_in",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Tọa độ GPS lúc vào ca (Kinh độ, Vĩ độ)",
                null=True,
                srid=4326,
                verbose_name="Tọa độ Check-in",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="location_check_out",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Tọa độ GPS lúc ra ca",
                null=True,
                srid=4326,
                verbose_name="Tọa độ Check-out",
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="thiet_bi_check_in",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Thiết bị In"
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="thiet_bi_check_out",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Thiết bị Out"
            ),
        ),
        migrations.AlterField(
            model_name="chamcong",
            name="vi_tri_hop_le",
            field=models.BooleanField(
                default=True,
                help_text="Hệ thống tự động kiểm tra bán kính mục tiêu",
                verbose_name="Đúng vị trí quy định?",
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="anh_xac_thuc",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="alive_check/%Y/%m/",
                verbose_name="Ảnh xác thực Alive",
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="ca_truc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_lan_kiem_tra",
                to="operations.phancongcatruc",
                verbose_name="Ca trực kiểm tra",
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="thoi_gian_gui_yeu_cau",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời điểm phát lệnh"
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="thoi_gian_phan_hoi",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm phản hồi"
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="toa_do_xac_thuc",
            field=models.CharField(
                blank=True,
                help_text="Tọa độ chuỗi lưu tạm thời từ Mobile app",
                max_length=100,
                null=True,
                verbose_name="Vị trí xác thực",
            ),
        ),
        migrations.AlterField(
            model_name="kiemtraquanso",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Đang chờ phản hồi"),
                    ("OK", "✅ Đã xác nhận (Hoàn thành)"),
                    ("MISSED", "❌ Bỏ lỡ (Không phản hồi)"),
                    ("LATE", "🕒 Phản hồi muộn"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Kết quả kiểm tra",
            ),
        ),
        migrations.AlterField(
            model_name="phancongcatruc",
            name="ca_lam_viec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.calamviec",
                verbose_name="Ca trực",
            ),
        ),
        migrations.AlterField(
            model_name="phancongcatruc",
            name="ngay_truc",
            field=models.DateField(
                db_index=True,
                help_text="Định dạng chuẩn: Ngày/Tháng/Năm",
                verbose_name="Ngày thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="phancongcatruc",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="vitrichot",
            name="muc_tieu",
            field=models.ForeignKey(
                help_text="Chọn khách hàng/mục tiêu quản lý vị trí trực này",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vi_tri_chot",
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ",
            ),
        ),
        migrations.AlterField(
            model_name="vitrichot",
            name="ten_vi_tri",
            field=models.CharField(
                help_text="VD: Cổng chính, Kho A, Tuần tra vòng ngoài",
                max_length=255,
                verbose_name="Tên vị trí trực",
            ),
        ),
    ]
