# Generated by Django 5.2.5 on 2026-06-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_update_related_names"),
        (
            "operations",
            "0006_alter_baocaodexuat_options_alter_baocaosuco_options_and_more",
        ),
    ]

    operations = []
