# Generated by Django 5.2.5 on 2026-06-02 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_cohoikinhdoanh_khach_hang_tiem_nang_and_more"),
        ("operations", "0007_merge_20260602_0856"),
        ("users", "0006_nhanvien_fcm_token_nhanvien_ngay_nghi_viec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baocaodexuat",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="thoi_gian_quyet_toan",
            field=models.DateTimeField(
                blank=True,
                help_text="Mốc thời gian dùng để truy vấn vào bảng lương (SSOT)",
                null=True,
                verbose_name="Thời điểm chốt đền bù",
            ),
        ),
        migrations.AddField(
            model_name="calamviec",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="di_muon_phut",
            field=models.IntegerField(
                default=0,
                help_text="Số phút vào ca trễ so với quy định",
                verbose_name="Đi muộn (phút)",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="phat_vi_pham",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Tổng tiền phạt vi phạm phát sinh trong ca trực này",
                max_digits=12,
                verbose_name="Tiền phạt ca trực",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="thuc_lam_gio",
            field=models.FloatField(
                default=0.0,
                help_text="Số giờ làm việc tính toán dựa trên thời gian check-in/out",
                verbose_name="Giờ làm thực tế",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="ve_som_phut",
            field=models.IntegerField(
                default=0,
                help_text="Số phút rời ca sớm so với quy định",
                verbose_name="Về sớm (phút)",
            ),
        ),
        migrations.AddField(
            model_name="kiemtraquanso",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AddField(
            model_name="vitrichot",
            name="tenant_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Tenant ID",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_de_xuat",
                to="clients.muctieu",
                verbose_name="Tại mục tiêu",
            ),
        ),
        migrations.AlterField(
            model_name="baocaodexuat",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_de_xuat",
                to="users.nhanvien",
                verbose_name="Nhân viên đề xuất",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="ca_truc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co",
                to="operations.phancongcatruc",
                verbose_name="Phiên trực liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_su_co",
                to="clients.muctieu",
                verbose_name="Địa điểm (Mục tiêu)",
            ),
        ),
    ]
