# Generated by Django 5.2.5 on 2026-06-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_kiemtraquanso_device_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='baocaosuco',
            new_name='operations__tenant__632773_idx',
            old_name='operations__tenant__5e5d69_idx',
        ),
        migrations.RenameIndex(
            model_name='baocaosuco',
            new_name='operations__tenant__1b72ff_idx',
            old_name='operations__tenant__7f68d2_idx',
        ),
        migrations.RenameIndex(
            model_name='chamcong',
            new_name='operations__tenant__40cc34_idx',
            old_name='operations__tenant__31fea6_idx',
        ),
        migrations.RenameIndex(
            model_name='phancongcatruc',
            new_name='operations__tenant__2b9916_idx',
            old_name='operations__tenant__68513a_idx',
        ),
    ]
