# Generated by Django 5.2.5 on 2026-06-11 for SCMD Pro migration-state alignment.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0014_alter_baocaodexuat_tenant_id_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chamcong",
            old_name="operations__tenant__40cc34_idx",
            new_name="ops_cc_tenant_checkin_idx",
        ),
    ]
