# Generated by GPT-5.5 Thinking for SCMD Pro operations domain completeness.

import core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_hr_phase_b_records"),
        ("operations", "0015_rename_operations__tenant__40cc34_idx_ops_cc_tenant_checkin_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("ma_yeu_cau", models.CharField(db_index=True, max_length=64, verbose_name="Mã yêu cầu")),
                ("loai_yeu_cau", models.CharField(choices=[("CHANGE_SHIFT", "Đổi ca"), ("SWAP_STAFF", "Đổi người trực"), ("OVERTIME", "Tăng ca"), ("CANCEL_SHIFT", "Hủy ca")], default="CHANGE_SHIFT", max_length=32, verbose_name="Loại yêu cầu")),
                ("ngay_mong_muon", models.DateField(blank=True, db_index=True, null=True, verbose_name="Ngày trực mong muốn")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("REJECTED", "Từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ly_do", models.TextField(blank=True, verbose_name="Lý do")),
                ("file_minh_chung", models.FileField(blank=True, null=True, upload_to="shift_change_requests/%Y/%m/", verbose_name="File minh chứng")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("ca_mong_muon", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_yeu_cau_doi_ca_mong_muon", to="operations.calamviec", verbose_name="Ca mong muốn")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_yeu_cau_doi_ca_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nguoi_yeu_cau", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_yeu_cau_doi_ca", to="users.nhanvien", verbose_name="Người yêu cầu")),
                ("nhan_vien_thay_the", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_yeu_cau_thay_the_ca", to="users.nhanvien", verbose_name="Nhân viên thay thế")),
                ("phan_cong_goc", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_yeu_cau_thay_doi", to="operations.phancongcatruc", verbose_name="Phân công gốc")),
                ("vi_tri_mong_muon", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_yeu_cau_doi_ca_mong_muon", to="operations.vitrichot", verbose_name="Vị trí mong muốn")),
            ],
            options={
                "verbose_name": "Yêu cầu đổi ca/tăng ca",
                "verbose_name_plural": "Yêu cầu đổi ca/tăng ca",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "created_at"], name="ops_shiftreq_tenant_stat_idx"),
                    models.Index(fields=["tenant_id", "nguoi_yeu_cau", "trang_thai"], name="ops_shiftreq_tenant_staff_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "ma_yeu_cau"), name="uq_shiftreq_tenant_code")],
            },
        ),
    ]
