# Generated by GPT-5.5 Thinking for SCMD Pro Phase C v2.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0016_shift_change_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftchangerequest",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Nháp"),
                    ("PENDING_APPROVAL", "Chờ duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("APPLIED", "Đã áp dụng"),
                    ("REJECTED", "Từ chối"),
                    ("CANCELLED", "Đã hủy"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=32,
                verbose_name="Trạng thái",
            ),
        ),
    ]
