# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tiêu đề Tờ trình"
                    ),
                ),
                (
                    "loai_de_xuat",
                    models.CharField(
                        choices=[
                            ("KE_HOACH", "📄 Kế hoạch KD/Vận hành"),
                            ("MUA_SAM", "🛒 Mua sắm / Trang bị"),
                            ("NHAN_SU", "👥 Nhân sự (Tuyển/Bổ nhiệm)"),
                            ("TAI_CHINH", "💰 Tài chính / Thanh toán"),
                            ("KHAC", "📝 Khác"),
                        ],
                        db_index=True,
                        default="KHAC",
                        max_length=20,
                        verbose_name="Loại",
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("NHAP", "Bản nháp"),
                            ("CHO_DUYET", "⏳ Đang trình duyệt"),
                            ("DA_DUYET", "✅ Đã phê duyệt"),
                            ("TU_CHOI", "❌ Đã từ chối"),
                            ("YEU_CAU_SUA", "✏️ Yêu cầu chỉnh sửa"),
                        ],
                        db_index=True,
                        default="CHO_DUYET",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="proposals/%Y/%m/",
                        verbose_name="Đính kèm",
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
                (
                    "nguoi_de_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals_created",
                        to="users.nhanvien",
                        verbose_name="Người trình",
                    ),
                ),
                (
                    "nguoi_duyet_hien_tai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals_pending",
                        to="users.nhanvien",
                        verbose_name="Người duyệt hiện tại",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tờ trình / Đề xuất",
                "verbose_name_plural": "02. Quản lý Tờ trình",
                "ordering": ["-ngay_tao"],
            },
        ),
        migrations.CreateModel(
            name="PheDuyetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hanh_dong",
                    models.CharField(
                        choices=[
                            ("GUI", "Gửi trình"),
                            ("DUYET", "Phê duyệt"),
                            ("CHUYEN", "Kính chuyển/Trình lên"),
                            ("TU_CHOI", "Từ chối"),
                            ("YEU_CAU_SUA", "Yêu cầu sửa"),
                        ],
                        max_length=20,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "y_kien",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ý kiến / Chỉ đạo"
                    ),
                ),
                (
                    "thoi_gian",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "nguoi_nhan_tiep_theo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_incoming",
                        to="users.nhanvien",
                        verbose_name="Chuyển đến",
                    ),
                ),
                (
                    "nguoi_xu_ly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.nhanvien",
                        verbose_name="Người xử lý",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflow.proposal",
                        verbose_name="Tờ trình",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký xử lý",
                "verbose_name_plural": "03. Lịch sử Phê duyệt",
                "ordering": ["thoi_gian"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tiêu đề"
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "han_chot",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Hạn chót (Deadline)",
                    ),
                ),
                (
                    "uu_tien",
                    models.CharField(
                        choices=[
                            ("THAP", "🟢 Thấp"),
                            ("TB", "🔵 Trung bình"),
                            ("CAO", "🟠 Cao"),
                            ("KHAN", "🔴 Khẩn cấp"),
                        ],
                        db_index=True,
                        default="TB",
                        max_length=20,
                        verbose_name="Độ ưu tiên",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("MOI", "Mới giao"),
                            ("DANG_LAM", "Đang thực hiện"),
                            ("CHO_DUYET", "Chờ nghiệm thu"),
                            ("HOAN_THANH", "Hoàn thành"),
                            ("HUY", "Đã hủy"),
                        ],
                        db_index=True,
                        default="MOI",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "tien_do",
                    models.IntegerField(
                        default=0,
                        help_text="Nhập từ 0 đến 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Tiến độ (%)",
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tasks/%Y/%m/",
                        verbose_name="Tài liệu đính kèm",
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật cuối"),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Liên quan Mục tiêu (Optional)",
                    ),
                ),
                (
                    "nguoi_giao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_giao",
                        to="users.nhanvien",
                        verbose_name="Người giao",
                    ),
                ),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_nhan",
                        to="users.nhanvien",
                        verbose_name="Người chịu trách nhiệm chính",
                    ),
                ),
                (
                    "nguoi_phoi_hop",
                    models.ManyToManyField(
                        blank=True,
                        related_name="task_phoi_hop",
                        to="users.nhanvien",
                        verbose_name="Người phối hợp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Công việc văn phòng",
                "verbose_name_plural": "01. Quản lý Công việc",
                "ordering": ["-ngay_tao"],
            },
        ),
    ]
