# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_cohoikinhdoanh_gia_tri_uoc_tinh_and_more"),
        ("users", "0004_alter_chucdanh_options_alter_nhanvien_options_and_more"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pheduyetlog",
            options={
                "ordering": ["thoi_gian"],
                "verbose_name": "Nhật ký phê duyệt",
                "verbose_name_plural": "03. Lịch sử Phê duyệt",
            },
        ),
        migrations.AlterModelOptions(
            name="proposal",
            options={
                "ordering": ["-ngay_tao"],
                "verbose_name": "Tờ trình",
                "verbose_name_plural": "02. Quản lý Tờ trình",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-ngay_tao"],
                "verbose_name": "Công việc",
                "verbose_name_plural": "01. Quản lý Công việc",
            },
        ),
        migrations.AlterField(
            model_name="pheduyetlog",
            name="hanh_dong",
            field=models.CharField(
                choices=[
                    ("GUI", "Gửi trình"),
                    ("DUYET", "Phê duyệt"),
                    ("CHUYEN", "Trình lên cấp trên"),
                    ("TU_CHOI", "Từ chối"),
                    ("YEU_CAU_SUA", "Yêu cầu sửa lại"),
                ],
                max_length=20,
                verbose_name="Hành động",
            ),
        ),
        migrations.AlterField(
            model_name="pheduyetlog",
            name="nguoi_nhan_tiep_theo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs_incoming",
                to="users.nhanvien",
                verbose_name="Người nhận tiếp theo",
            ),
        ),
        migrations.AlterField(
            model_name="pheduyetlog",
            name="thoi_gian",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời điểm xử lý"
            ),
        ),
        migrations.AlterField(
            model_name="pheduyetlog",
            name="y_kien",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ý kiến chỉ đạo"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="file_dinh_kem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proposals/%Y/%m/",
                verbose_name="Hồ sơ đính kèm",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="loai_de_xuat",
            field=models.CharField(
                choices=[
                    ("KE_HOACH", "📄 Kế hoạch KD/Vận hành"),
                    ("MUA_SAM", "🛒 Mua sắm / Trang bị"),
                    ("NHAN_SU", "👥 Nhân sự (Tuyển/Bổ nhiệm)"),
                    ("TAI_CHINH", "💰 Tài chính / Thanh toán"),
                    ("KHAC", "📝 Khác"),
                ],
                db_index=True,
                default="KHAC",
                max_length=20,
                verbose_name="Loại tờ trình",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="ngay_cap_nhat",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật cuối"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="ngay_tao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày khởi tạo"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="nguoi_de_xuat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals_created",
                to="users.nhanvien",
                verbose_name="Người khởi tạo",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="nguoi_duyet_hien_tai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals_pending",
                to="users.nhanvien",
                verbose_name="Người đang thụ lý",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="noi_dung",
            field=models.TextField(verbose_name="Nội dung trình duyệt"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="tieu_de",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Tiêu đề tờ trình"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("NHAP", "Bản nháp"),
                    ("CHO_DUYET", "⏳ Đang trình duyệt"),
                    ("DA_DUYET", "✅ Đã phê duyệt"),
                    ("TU_CHOI", "❌ Đã từ chối"),
                    ("YEU_CAU_SUA", "✏️ Yêu cầu chỉnh sửa"),
                ],
                db_index=True,
                default="NHAP",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="file_dinh_kem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tasks/%Y/%m/",
                verbose_name="Tài liệu/Báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.muctieu",
                verbose_name="Mục tiêu bảo vệ liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="nguoi_giao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_giao",
                to="users.nhanvien",
                verbose_name="Người giao việc",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="nguoi_phoi_hop",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_phoi_hop",
                to="users.nhanvien",
                verbose_name="Nhân sự phối hợp",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tien_do",
            field=models.IntegerField(
                default=0,
                help_text="Nhập giá trị từ 0 đến 100",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Tiến độ (%)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tieu_de",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Tiêu đề công việc"
            ),
        ),
    ]
