# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BangLuongThang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_bang_luong",
                    models.CharField(
                        default="Bảng lương tháng ...",
                        max_length=200,
                        verbose_name="Tên bảng lương",
                    ),
                ),
                ("thang", models.IntegerField(default=12, verbose_name="Tháng")),
                ("nam", models.IntegerField(default=2025, verbose_name="Năm")),
                (
                    "ngay_chot_cong",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày chốt công"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("NHAP", "Dự thảo (Đang tính)"),
                            ("CHO_DUYET", "Chờ KTT duyệt"),
                            ("DA_PHAT_HANH", "Đã duyệt & Phát hành (NV xem được)"),
                        ],
                        default="NHAP",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "tong_chi_tra",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng chi trả",
                    ),
                ),
                (
                    "tong_gio_cong",
                    models.FloatField(default=0, verbose_name="Tổng giờ công"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "1. Bảng lương Tháng",
                "verbose_name_plural": "Quản lý Kỳ lương",
            },
        ),
        migrations.CreateModel(
            name="CauHinhLuong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "luong_co_ban_ngay",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Lương cơ bản (BHXH)",
                    ),
                ),
                (
                    "phu_cap_trach_nhiem",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="P.C Trách nhiệm",
                    ),
                ),
                (
                    "phu_cap_xang_xe",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="P.C Xăng xe",
                    ),
                ),
                (
                    "phu_cap_an_uong",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="P.C Ăn uống",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ Lương (Cá nhân)",
                "verbose_name_plural": "Hồ sơ Lương (Cá nhân)",
            },
        ),
        migrations.CreateModel(
            name="ChiTietLuong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tong_gio_lam",
                    models.FloatField(default=0, verbose_name="Tổng giờ làm"),
                ),
                (
                    "so_ngay_nghi",
                    models.IntegerField(default=0, verbose_name="Số ngày nghỉ"),
                ),
                (
                    "luong_chinh",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Lương chính",
                    ),
                ),
                (
                    "thuong_chuyen_can",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Thưởng chuyên cần",
                    ),
                ),
                (
                    "phu_cap_khac",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phụ cấp khác",
                    ),
                ),
                (
                    "ung_luong",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tạm ứng",
                    ),
                ),
                (
                    "phat_vi_pham",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phạt vi phạm",
                    ),
                ),
                (
                    "tien_dong_phuc",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tiền đồng phục",
                    ),
                ),
                (
                    "tien_den_bu",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tiền đền bù",
                    ),
                ),
                (
                    "bao_hiem",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="BHXH/BHYT",
                    ),
                ),
                (
                    "phi_cong_doan",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phí Công đoàn",
                    ),
                ),
                (
                    "thuc_lanh",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Thực lãnh",
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Phiếu lương NV",
                "verbose_name_plural": "Phiếu lương NV",
            },
        ),
        migrations.CreateModel(
            name="SoQuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_phieu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu"
                    ),
                ),
                (
                    "loai_phieu",
                    models.CharField(
                        choices=[("THU", "Phiếu Thu"), ("CHI", "Phiếu Chi")],
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "hang_muc",
                    models.CharField(
                        choices=[
                            ("TAM_UNG", "Chi tạm ứng lương"),
                            ("LUONG", "Chi trả lương tháng"),
                            ("PHI_DV", "Thu phí dịch vụ (Khách hàng)"),
                            ("MUA_SAM", "Chi mua sắm vật tư"),
                            ("KHAC", "Thu chi khác"),
                        ],
                        max_length=20,
                        verbose_name="Hạng mục",
                    ),
                ),
                (
                    "so_tien",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Số tiền"
                    ),
                ),
                (
                    "ngay_lap",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày lập"
                    ),
                ),
                ("dien_giai", models.TextField(verbose_name="Diễn giải")),
                (
                    "chung_tu_goc",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ketoan/chungtu/",
                        verbose_name="Ảnh chứng từ",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("NHAP", "Bản nháp"),
                            ("CHO_DUYET", "Chờ KTT duyệt"),
                            ("DA_DUYET", "Đã duyệt"),
                            ("TU_CHOI", "Từ chối"),
                        ],
                        default="NHAP",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sổ Thu Chi",
                "verbose_name_plural": "Sổ Quỹ Tiền Mặt/Ngân Hàng",
                "ordering": ["-ngay_lap"],
            },
        ),
    ]
