# Generated by Django 5.2.5 on 2025-12-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("clients", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bangluongthang",
            name="nguoi_duyet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Kế toán trưởng",
            ),
        ),
        migrations.AddField(
            model_name="cauhinhluong",
            name="nhan_vien",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cau_hinh_luong",
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="chitietluong",
            name="bang_luong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet",
                to="accounting.bangluongthang",
            ),
        ),
        migrations.AddField(
            model_name="chitietluong",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.nhanvien"
            ),
        ),
        migrations.AddField(
            model_name="soquy",
            name="hop_dong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.hopdong",
                verbose_name="Hợp đồng KH",
            ),
        ),
        migrations.AddField(
            model_name="soquy",
            name="nguoi_duyet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_phieu_duyet",
                to="users.nhanvien",
                verbose_name="Kế toán trưởng duyệt",
            ),
        ),
        migrations.AddField(
            model_name="soquy",
            name="nguoi_lap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_phieu_lap",
                to="users.nhanvien",
                verbose_name="Người lập",
            ),
        ),
        migrations.AddField(
            model_name="soquy",
            name="nhan_vien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bangluongthang",
            unique_together={("thang", "nam")},
        ),
        migrations.AlterUniqueTogether(
            name="chitietluong",
            unique_together={("bang_luong", "nhan_vien")},
        ),
    ]
