# -*- coding: utf-8 -*-
# Generated by Django 4.x.x on 2026-05-16 00:00
from django.db import migrations, models
import uuid
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
import logging

logger = logging.getLogger(__name__)

def populate_tenant_ids(apps, schema_editor):
    """
    Populates the tenant_id for existing records in accounting models
    with the SCMD_ORGANIZATION_ID from settings.
    """
    if not hasattr(settings, 'SCMD_ORGANIZATION_ID'):
        logger.error("SCMD_ORGANIZATION_ID is not defined in settings. Cannot populate tenant_ids.")
        raise ImproperlyConfigured("SCMD_ORGANIZATION_ID is not defined in settings. Cannot run this migration.")
    
    scmd_org_setting = settings.SCMD_ORGANIZATION_ID
    scmd_org_id = scmd_org_setting if isinstance(scmd_org_setting, uuid.UUID) else uuid.UUID(str(scmd_org_setting))
    
    models_to_update = [
        apps.get_model('accounting', 'CauHinhLuong'),
        apps.get_model('accounting', 'BangLuongThang'),
        apps.get_model('accounting', 'ChiTietLuong'),
    ]

    for Model in models_to_update:
        logger.info(f"Populating tenant_id for existing {Model.__name__} records...")
        # Update all records where tenant_id might be null or a different default UUID
        # This ensures all *existing* records get the correct SCMD_ORGANIZATION_ID.
        updated_count = Model.objects.all().update(tenant_id=scmd_org_id)
        logger.info(f"Updated {updated_count} {Model.__name__} records with tenant_id={scmd_org_id}.")

def reverse_populate_tenant_ids(apps, schema_editor):
    """
    Reverse operation: Does nothing as tenant_id is a critical field now.
    If rolling back, the field would be removed.
    """
    logger.info("Reverse migration for tenant_id population: No specific action needed for data.")
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'), # Assuming '0001_initial' is the previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhluong',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
        migrations.AddField(
            model_name='bangluongthang',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
        migrations.AddField(
            model_name='chitietluong',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
        migrations.RunPython(populate_tenant_ids, reverse_populate_tenant_ids),
    ]
