# Generated by Django 5.2.5 on 2026-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bangluongthang",
            name="nam",
            field=models.IntegerField(default=2026, verbose_name="Năm"),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="thang",
            field=models.IntegerField(default=3, verbose_name="Tháng"),
        ),
    ]
