# Generated by Django 5.2.5 on 2026-03-21 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_bangluongthang_nam_alter_bangluongthang_thang"),
        ("users", "0003_alter_nhanvien_loai_hop_dong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bangluongthang",
            options={
                "ordering": ["-nam", "-thang"],
                "verbose_name": "Kỳ lương hệ thống",
                "verbose_name_plural": "1. Quản lý Kỳ lương",
            },
        ),
        migrations.AlterModelOptions(
            name="cauhinhluong",
            options={
                "verbose_name": "Hồ sơ Lương cá nhân",
                "verbose_name_plural": "Hồ sơ Lương cá nhân",
            },
        ),
        migrations.AlterModelOptions(
            name="chitietluong",
            options={
                "verbose_name": "Phiếu lương cá nhân",
                "verbose_name_plural": "Phiếu lương cá nhân",
            },
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ngày tạo bảng kê"
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="nam",
            field=models.IntegerField(default=2026, verbose_name="Năm quyết toán"),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="ngay_chot_cong",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Ngày cuối cùng hệ thống ghi nhận giờ làm việc cho kỳ lương này.",
                verbose_name="Ngày chốt dữ liệu công",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="nguoi_duyet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Người phê duyệt (KTT/GĐ)",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="ten_bang_luong",
            field=models.CharField(
                default="Bảng lương tháng ...",
                help_text="Ví dụ: Bảng lương mục tiêu Vincity - Tháng 03/2026",
                max_length=200,
                verbose_name="Tên bảng lương",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="thang",
            field=models.IntegerField(
                default=3,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tháng lương",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="tong_chi_tra",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Tổng số tiền thực lĩnh của toàn bộ nhân viên trong kỳ.",
                max_digits=15,
                verbose_name="Tổng ngân sách chi trả",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="tong_gio_cong",
            field=models.FloatField(
                default=0,
                help_text="Tổng hợp toàn bộ giờ làm việc của nhân sự trong tháng.",
                verbose_name="Tổng giờ công hệ thống",
            ),
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("NHAP", "Dự thảo (Đang tính toán)"),
                    ("CHO_DUYET", "Chờ Kế toán trưởng duyệt"),
                    ("DA_PHAT_HANH", "Đã duyệt & Phát hành (Nhân viên đã xem)"),
                ],
                default="NHAP",
                max_length=20,
                verbose_name="Trạng thái phê duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="cauhinhluong",
            name="luong_co_ban_ngay",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Mức lương căn bản dùng để tính bảo hiểm và các chế độ nhà nước.",
                max_digits=12,
                verbose_name="Mức lương đóng BHXH",
            ),
        ),
        migrations.AlterField(
            model_name="cauhinhluong",
            name="nhan_vien",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cau_hinh_luong",
                to="users.nhanvien",
                verbose_name="Nhân viên thụ hưởng",
            ),
        ),
        migrations.AlterField(
            model_name="cauhinhluong",
            name="phu_cap_an_uong",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Hỗ trợ tiền ăn trực ca theo quy định của SCMD.",
                max_digits=12,
                verbose_name="Phụ cấp ăn ca",
            ),
        ),
        migrations.AlterField(
            model_name="cauhinhluong",
            name="phu_cap_trach_nhiem",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Phụ cấp dành cho các vị trí chỉ huy, đội trưởng, hoặc mục tiêu trọng yếu.",
                max_digits=12,
                verbose_name="Phụ cấp trách nhiệm",
            ),
        ),
        migrations.AlterField(
            model_name="cauhinhluong",
            name="phu_cap_xang_xe",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Hỗ trợ chi phí di chuyển giữa các mục tiêu bảo vệ.",
                max_digits=12,
                verbose_name="Phụ cấp đi lại/Xăng xe",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="bang_luong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet",
                to="accounting.bangluongthang",
                verbose_name="Thuộc kỳ lương",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="bao_hiem",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Khấu trừ BHXH/BHYT",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="ghi_chu",
            field=models.TextField(
                blank=True,
                help_text="Giải trình các khoản thưởng/phạt đặc thù.",
                verbose_name="Ghi chú nghiệp vụ",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="luong_chinh",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Lương theo công trạng",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="phat_vi_pham",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Phạt kỷ luật/Vi phạm",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="phi_cong_doan",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Kinh phí Công đoàn",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="phu_cap_khac",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Tổng phụ cấp khác",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="so_ngay_nghi",
            field=models.IntegerField(
                default=0, verbose_name="Số ngày nghỉ phép/không lương"
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="thuc_lanh",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Thực lĩnh cuối kỳ",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="tien_den_bu",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Bồi thường thiệt hại (nếu có)",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="tien_dong_phuc",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Tiền quân trang/Đồng phục",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="tong_gio_lam",
            field=models.FloatField(default=0, verbose_name="Tổng giờ làm việc"),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="ung_luong",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Khoản tạm ứng"
            ),
        ),
    ]
