# Generated by Django 5.2.5 on 2026-06-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_add_tenant_id_to_accounting_models"),
        ("accounting", "0004_alter_bangluongthang_options_and_more"),
    ]

    operations = []
