# Generated by Django 5.2.5 on 2026-06-02 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_merge_20260602_0856"),
        ("users", "0006_nhanvien_fcm_token_nhanvien_ngay_nghi_viec_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bangluongthang",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="chitietluong",
            unique_together={("bang_luong", "nhan_vien", "tenant_id")},
        ),
        migrations.AlterField(
            model_name="bangluongthang",
            name="thang",
            field=models.IntegerField(
                default=6,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tháng lương",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="luong_chinh",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Lương khoán (từ CRM)",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="tien_den_bu",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Khấu trừ đền bù sự cố",
            ),
        ),
        migrations.AlterField(
            model_name="chitietluong",
            name="tien_dong_phuc",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Khấu trừ vật tư/Đồng phục",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bangluongthang",
            unique_together={("thang", "nam", "tenant_id")},
        ),
        migrations.CreateModel(
            name="PhanHoiLuong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="Tenant ID"),
                ),
                (
                    "noi_dung",
                    models.TextField(verbose_name="Nội dung phản hồi/thắc mắc"),
                ),
                (
                    "phan_hoi_admin",
                    models.TextField(blank=True, verbose_name="Phản hồi từ kế toán"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("MOI", "Mới tiếp nhận"),
                            ("DANG_XU_LY", "Đang xử lý"),
                            ("DA_GIAI_QUYET", "Đã giải quyết"),
                            ("TU_CHOI", "Từ chối"),
                        ],
                        default="MOI",
                        max_length=20,
                        verbose_name="Trạng thái xử lý",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chi_tiet_luong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_sach_phan_hoi",
                        to="accounting.chitietluong",
                        verbose_name="Phiếu lương khiếu nại",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.nhanvien",
                        verbose_name="Nhân viên phản hồi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phản hồi lương",
                "verbose_name_plural": "2. Phản hồi lương (Dispute)",
                "ordering": ["-created_at"],
            },
        ),
    ]
