# Generated by Django 5.2.5 on 2026-06-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_payroll_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bangluongthang',
            new_name='accounting__tenant__a93af4_idx',
            old_name='accounting_b_tenant__44b6e0_idx',
        ),
        migrations.RenameIndex(
            model_name='bangluongthang',
            new_name='accounting__tenant__9139dd_idx',
            old_name='accounting_b_tenant__956a8d_idx',
        ),
    ]
