# Generated by Django 5.2.5 on 2026-06-08 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_rename_accounting_b_tenant__44b6e0_idx_accounting__tenant__a93af4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoiluong',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Tenant ID'),
        ),
    ]
