# Generated by GPT-5.5 Thinking for SCMD Pro payroll domain completeness.

import core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_hr_phase_b_records"),
        ("accounting", "0013_payroll_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TamUngLuong",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_phieu", models.CharField(db_index=True, max_length=64, verbose_name="Số phiếu tạm ứng")),
                ("ngay_de_nghi", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Ngày đề nghị")),
                ("so_tien", models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền tạm ứng")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("PAID", "Đã chi"), ("DEDUCTED", "Đã khấu trừ"), ("REJECTED", "Từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ly_do", models.TextField(blank=True, verbose_name="Lý do")),
                ("file_minh_chung", models.FileField(blank=True, null=True, upload_to="tam_ung_luong/%Y/%m/", verbose_name="File/bằng chứng")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("bang_luong_du_kien", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_tam_ung_luong", to="accounting.bangluongthang", verbose_name="Kỳ lương dự kiến khấu trừ")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_tam_ung_luong_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_tam_ung_luong", to="users.nhanvien", verbose_name="Nhân viên")),
            ],
            options={
                "verbose_name": "Tạm ứng lương",
                "verbose_name_plural": "4. Tạm ứng lương",
                "ordering": ["-ngay_de_nghi", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_de_nghi"], name="acc_adv_tenant_stat_date_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "trang_thai"], name="acc_adv_tenant_staff_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_phieu"), name="uq_adv_tenant_voucher")],
            },
        ),
        migrations.CreateModel(
            name="KhoanKhauTruNhanVien",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.UUIDField(db_index=True, default=core.managers.organization_id, editable=False, verbose_name="Tenant ID")),
                ("so_chung_tu", models.CharField(db_index=True, max_length=64, verbose_name="Số chứng từ")),
                ("loai_khau_tru", models.CharField(choices=[("TAM_UNG", "Khấu trừ tạm ứng"), ("DONG_PHUC", "Đồng phục/công cụ"), ("DEN_BU", "Đền bù"), ("VI_PHAM", "Vi phạm/kỷ luật"), ("BAO_HIEM", "Bảo hiểm"), ("KHAC", "Khác")], default="KHAC", max_length=32, verbose_name="Loại khấu trừ")),
                ("ngay_ap_dung", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Ngày áp dụng")),
                ("so_tien", models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Số tiền khấu trừ")),
                ("trang_thai", models.CharField(choices=[("DRAFT", "Nháp"), ("PENDING_APPROVAL", "Chờ duyệt"), ("APPROVED", "Đã duyệt"), ("APPLIED", "Đã áp dụng kỳ lương"), ("REJECTED", "Từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="DRAFT", max_length=32, verbose_name="Trạng thái")),
                ("ly_do", models.TextField(blank=True, verbose_name="Lý do")),
                ("file_minh_chung", models.FileField(blank=True, null=True, upload_to="khoan_khau_tru/%Y/%m/", verbose_name="File/bằng chứng")),
                ("ngay_duyet", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Tạo lúc")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc")),
                ("bang_luong_du_kien", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_khoan_khau_tru", to="accounting.bangluongthang", verbose_name="Kỳ lương dự kiến")),
                ("nguoi_duyet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_khoan_khau_tru_da_duyet", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt")),
                ("nhan_vien", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cac_khoan_khau_tru", to="users.nhanvien", verbose_name="Nhân viên")),
                ("tam_ung", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cac_khoan_khau_tru", to="accounting.tamungluong", verbose_name="Phiếu tạm ứng liên quan")),
            ],
            options={
                "verbose_name": "Khoản khấu trừ nhân viên",
                "verbose_name_plural": "5. Khoản khấu trừ nhân viên",
                "ordering": ["-ngay_ap_dung", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "trang_thai", "ngay_ap_dung"], name="acc_ded_tenant_stat_date_idx"),
                    models.Index(fields=["tenant_id", "nhan_vien", "loai_khau_tru"], name="acc_ded_tenant_staff_type_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant_id", "so_chung_tu"), name="uq_ded_tenant_doc_no")],
            },
        ),
    ]
